import { PROVIDERS } from "./providers.js";
import { buildTtsProviderModels } from "./ttsModels.js";

// Provider models - Single source of truth
// Key = alias (cc, cx, gc, qw, if, ag, gh for OAuth; id for API Key)
// Field "provider" for special cases (e.g. AntiGravity models that call different backends)

const CODEX_REVIEW_SUFFIX = "-review";

function withCodexReviewModels(models) {
  return models.flatMap((model) => {
    if ((model.type || "llm") !== "llm" || model.id.endsWith(CODEX_REVIEW_SUFFIX)) {
      return [model];
    }

    return [
      model,
      {
        ...model,
        id: `${model.id}${CODEX_REVIEW_SUFFIX}`,
        name: `${model.name} Review`,
        upstreamModelId: model.upstreamModelId || model.id,
        quotaFamily: "review",
      },
    ];
  });
}

export const PROVIDER_MODELS = {
  // OAuth Providers (using alias)
  cc: [  // Claude Code
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4-5-20251101", name: "Claude 4.5 Opus" },
    { id: "claude-sonnet-4-5-20250929", name: "Claude 4.5 Sonnet" },
    { id: "claude-haiku-4-5-20251001", name: "Claude 4.5 Haiku" },
  ],
  cx: withCodexReviewModels([  // OpenAI Codex
    { id: "gpt-5.5", name: "GPT 5.5" },
    { id: "gpt-5.5-xhigh", name: "GPT 5.5 (xHigh)" },
    { id: "gpt-5.5-high", name: "GPT 5.5 (High)" },
    { id: "gpt-5.5-medium", name: "GPT 5.5 (Medium)" },
    { id: "gpt-5.5-low", name: "GPT 5.5 (Low)" },
    { id: "gpt-5.4", name: "GPT 5.4" },
    { id: "gpt-5.3-codex", name: "GPT 5.3 Codex" },
    { id: "gpt-5.3-codex-xhigh", name: "GPT 5.3 Codex (xHigh)" },
    { id: "gpt-5.3-codex-high", name: "GPT 5.3 Codex (High)" },
    { id: "gpt-5.3-codex-low", name: "GPT 5.3 Codex (Low)" },
    { id: "gpt-5.3-codex-none", name: "GPT 5.3 Codex (None)" },
    { id: "gpt-5.2", name: "GPT 5.2" },
    // Image models (uses image_generation tool, requires Plus/Pro plan)
    { id: "gpt-5.4-image", name: "GPT 5.4 Image", type: "image", capabilities: ["text2img", "edit"], params: ["size", "quality", "background", "image_detail", "output_format"] },
    { id: "gpt-5.3-image", name: "GPT 5.3 Image", type: "image", capabilities: ["text2img", "edit"], params: ["size", "quality", "background", "image_detail", "output_format"] },
    { id: "gpt-5.2-image", name: "GPT 5.2 Image", type: "image", capabilities: ["text2img", "edit"], params: ["size", "quality", "background", "image_detail", "output_format"] },
  ]),
  gc: [  // Gemini CLI
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "gemini-3-pro-preview", name: "Gemini 3 Pro Preview" },
  ],
  nous: [  // Nous Portal
    { id: "stepfun/step-3.7-flash:free", name: "StepFun Step 3.7 Flash (Free)" },
    { id: "stepfun/step-3.5-flash", name: "StepFun Step 3.5 Flash" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "google/lyria-3-clip-preview", name: "Google Lyria 3 Clip Preview" },
    { id: "google/lyria-3-pro-preview", name: "Google Lyria 3 Pro Preview" },
    { id: "openrouter/owl-alpha", name: "OpenRouter Owl Alpha" },
  ],
  qw: [  // Qwen Code
    // { id: "qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "qwen3-coder-flash", name: "Qwen3 Coder Flash" },
    { id: "vision-model", name: "Qwen3 Vision Model" },
    { id: "coder-model", name: "Qwen3.6 Coder Model" },
  ],
  if: [  // iFlow AI
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "qwen3-max", name: "Qwen3 Max" },
    { id: "qwen3-vl-plus", name: "Qwen3 VL Plus" },
    { id: "qwen3-max-preview", name: "Qwen3 Max Preview" },
    { id: "qwen3-235b", name: "Qwen3 235B A22B" },
    { id: "qwen3-235b-a22b-instruct", name: "Qwen3 235B A22B Instruct" },
    { id: "qwen3-235b-a22b-thinking-2507", name: "Qwen3 235B A22B Thinking" },
    { id: "qwen3-32b", name: "Qwen3 32B" },
    { id: "kimi-k2", name: "Kimi K2" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2 Exp" },
    { id: "deepseek-v3.1", name: "DeepSeek V3.1 Terminus" },
    { id: "deepseek-v3", name: "DeepSeek V3 671B" },
    { id: "deepseek-r1", name: "DeepSeek R1" },
    { id: "glm-4.7", name: "GLM 4.7" },
    { id: "iflow-rome-30ba3b", name: "iFlow ROME" },
  ],
  ag: [  // Antigravity - special case: models call different backends
    { id: "gemini-3.1-pro-high", name: "Gemini 3 Pro High" },
    { id: "gemini-3.1-pro-low", name: "Gemini 3 Pro Low" },
    { id: "gemini-3-flash", name: "Gemini 3 Flash", thinking: false }, // AG strips thinking for this model
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4-6-thinking", name: "Claude Opus 4.6 Thinking" },
    { id: "gpt-oss-120b-medium", name: "GPT OSS 120B Medium" },
  ],
  gh: [  // GitHub Copilot - OpenAI models
    { id: "gpt-3.5-turbo", name: "GPT-3.5 Turbo" },
    { id: "gpt-4", name: "GPT-4" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o mini" },
    { id: "gpt-4.1", name: "GPT-4.1" },
    { id: "gpt-5-mini", name: "GPT-5 Mini" },
    { id: "gpt-5.2", name: "GPT-5.2" },
    { id: "gpt-5.2-codex", name: "GPT-5.2 Codex" },
    { id: "gpt-5.3-codex", name: "GPT-5.3 Codex" },
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
    // GitHub Copilot - Anthropic models
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "claude-sonnet-4", name: "Claude Sonnet 4" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
    // GitHub Copilot - Google models
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash" },
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro" },
    // GitHub Copilot - Other models
    { id: "grok-code-fast-1", name: "Grok Code Fast 1" },
    { id: "oswe-vscode-prime", name: "Raptor Mini" },
    { id: "goldeneye-free-auto", name: "GoldenEye" },
    // GitHub Copilot - Embedding models
    { id: "text-embedding-3-small", name: "Text Embedding 3 Small (GitHub)", type: "embedding" },
    { id: "text-embedding-3-large", name: "Text Embedding 3 Large (GitHub)", type: "embedding" },
  ],
  qd: [  // Qoder - tier + frontier models (server-published catalog)
    { id: "auto", name: "Qoder Auto" },
    { id: "ultimate", name: "Qoder Ultimate" },
    { id: "performance", name: "Qoder Performance" },
    { id: "efficient", name: "Qoder Efficient" },
    { id: "lite", name: "Qoder Lite" },
    { id: "qmodel", name: "Qwen 3.6 Plus (Qoder)" },
    { id: "dmodel", name: "DeepSeek V4 Pro (Qoder)" },
    { id: "dfmodel", name: "DeepSeek V4 Flash (Qoder)" },
    { id: "gm51model", name: "GLM 5.1 (Qoder)" },
    { id: "kmodel", name: "Kimi K2.6 (Qoder)" },
    { id: "mmodel", name: "MiniMax M2.7 (Qoder)" },
  ],
  kr: [  // Kiro AI
    // { id: "claude-opus-4.5", name: "Claude Opus 4.5" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-haiku-4.5", name: "Claude Haiku 4.5" },
    { id: "deepseek-3.2", name: "DeepSeek 3.2", strip: ["image", "audio"] },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next", strip: ["image", "audio"] },
    { id: "glm-5", name: "GLM 5" },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-opus-4.7", name: "Claude Opus 4.7" },
  ],
  cu: [  // Cursor IDE
    { id: "default", name: "Auto (Server Picks)" },
    { id: "claude-4.5-opus-high-thinking", name: "Claude 4.5 Opus High Thinking" },
    { id: "claude-4.5-opus-high", name: "Claude 4.5 Opus High" },
    { id: "claude-4.5-sonnet-thinking", name: "Claude 4.5 Sonnet Thinking" },
    { id: "claude-4.5-sonnet", name: "Claude 4.5 Sonnet" },
    { id: "claude-4.5-haiku", name: "Claude 4.5 Haiku" },
    { id: "claude-4.5-opus", name: "Claude 4.5 Opus" },
    { id: "gpt-5.2-codex", name: "GPT 5.2 Codex" },
    { id: "claude-4.6-opus-max", name: "Claude 4.6 Opus Max" },
    { id: "claude-4.6-sonnet-medium-thinking", name: "Claude 4.6 Sonnet Medium Thinking" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "gpt-5.2", name: "GPT 5.2" },
    { id: "gpt-5.3-codex", name: "GPT 5.3 Codex" },
  ],
  kmc: [  // Kimi Coding
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2.5-thinking", name: "Kimi K2.5 Thinking" },
    { id: "kimi-latest", name: "Kimi Latest" },
  ],
  kc: [  // KiloCode
    { id: "anthropic/claude-sonnet-4-20250514", name: "Claude Sonnet 4" },
    { id: "anthropic/claude-opus-4-20250514", name: "Claude Opus 4" },
    { id: "google/gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "openai/gpt-4.1", name: "GPT-4.1" },
    { id: "openai/o3", name: "o3" },
    { id: "deepseek/deepseek-chat", name: "DeepSeek Chat" },
    { id: "deepseek/deepseek-reasoner", name: "DeepSeek Reasoner" },
  ],
  "opencode-go": [  // OpenCode Go subscription (API key)
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "qwen3.5-plus", name: "Qwen 3.5 Plus" },
    { id: "qwen3.6-plus", name: "Qwen 3.6 Plus" },
    { id: "mimo-v2-pro", name: "MiMo V2 Pro" },
    { id: "mimo-v2-omni", name: "MiMo V2 Omni" },
    { id: "minimax-m2.7", name: "MiniMax M2.7", targetFormat: "claude" },
    { id: "minimax-m2.5", name: "MiniMax M2.5", targetFormat: "claude" },
  ],
  oc: [  // OpenCode
    // { id: "nemotron-3-super-free", name: "Nemotron 3 Super" },
    // { id: "qwen3.6-plus-free", name: "Qwen 3.6 Plus" },
    // { id: "big-pickle", name: "Big Pickle", targetFormat: "claude" },
    // { id: "minimax-m2.5-free", name: "MiniMax M2.5", targetFormat: "claude" },
    // { id: "trinity-large-preview-free", name: "Trinity Large Preview" },
  ],

  cl: [  // Cline — free/low-cost working models only
    { id: "minimax/minimax-m2.5", name: "MiniMax M2.5" },
    { id: "minimax/minimax-m3", name: "MiniMax M3" },
    { id: "kwaipilot/kat-coder-pro", name: "KAT Coder Pro", upstreamModelId: "kwaipilot/kat-coder-pro-v1" },
  ],

  "cline-apikey": [  // Cline API Key
    { id: "qwen/qwen3.7-plus", name: "Qwen3.7 Plus" },
    { id: "minimax/minimax-m2.5", name: "MiniMax M2.5" },
    { id: "minimax/minimax-m3", name: "MiniMax M3" },
    { id: "kwaipilot/kat-coder-pro-v1", name: "KAT Coder Pro v1" },
    { id: "kwaipilot/kat-coder-pro-v2", name: "KAT Coder Pro v2" },
  ],

  cb: [  // CodeBuddy
    { id: "default", name: "Default" },
    { id: "lite", name: "Lite" },
    { id: "reasoning", name: "Reasoning" },
    { id: "gpt-5", name: "GPT-5" },
    { id: "gpt-4", name: "GPT-4" },
    { id: "claude-sonnet-4", name: "Claude Sonnet 4" },
    { id: "deepseek-v3.1", name: "DeepSeek V3.1" },
    { id: "glm-4.7", name: "GLM 4.7" },
  ],

  // API Key Providers (alias = id)
  glb: [
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2-pro", name: "MiMo V2 Pro" },
    { id: "mimo-v2-flash", name: "MiMo V2 Flash" },
    { id: "mimo-v2-omni", name: "MiMo V2 Omni" },
    { id: "google/gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview" },
    { id: "zai-org/GLM-5.1-FP8", name: "GLM 5.1 FP8" },
  ],
  gitlawb: [
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2-pro", name: "MiMo V2 Pro" },
    { id: "mimo-v2-flash", name: "MiMo V2 Flash" },
    { id: "mimo-v2-omni", name: "MiMo V2 Omni" },
    { id: "google/gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview" },
    { id: "zai-org/GLM-5.1-FP8", name: "GLM 5.1 FP8" },
  ],
  "glb-mimo": [
    { id: "minimax/minimax-m3", name: "MiniMax: MiniMax M3" },
    { id: "stepfun/step-3.7-flash", name: "StepFun: Step 3.7 Flash" },
    { id: "anthropic/claude-opus-4.8-fast", name: "Anthropic: Claude Opus 4.8 (Fast)" },
    { id: "anthropic/claude-opus-4.8", name: "Anthropic: Claude Opus 4.8" },
    { id: "qwen/qwen3.7-max", name: "Qwen: Qwen3.7 Max" },
    { id: "x-ai/grok-build-0.1", name: "xAI: Grok Build 0.1" },
    { id: "google/gemini-3.5-flash", name: "Google: Gemini 3.5 Flash" },
    { id: "anthropic/claude-opus-4.7-fast", name: "Anthropic: Claude Opus 4.7 (Fast)" },
    { id: "perceptron/perceptron-mk1", name: "Perceptron: Perceptron Mk1" },
    { id: "inclusionai/ring-2.6-1t", name: "inclusionAI: Ring-2.6-1T" },
    { id: "google/gemini-3.1-flash-lite", name: "Google: Gemini 3.1 Flash Lite" },
    { id: "openai/gpt-chat-latest", name: "OpenAI: GPT Chat Latest" },
    { id: "x-ai/grok-4.3", name: "xAI: Grok 4.3" },
    { id: "ibm-granite/granite-4.1-8b", name: "IBM: Granite 4.1 8B" },
    { id: "mistralai/mistral-medium-3-5", name: "Mistral: Mistral Medium 3.5" },
    { id: "openrouter/owl-alpha", name: "Owl Alpha" },
    { id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", name: "NVIDIA: Nemotron 3 Nano Omni (free)" },
    { id: "poolside/laguna-xs.2:free", name: "Poolside: Laguna XS.2 (free)" },
    { id: "poolside/laguna-m.1:free", name: "Poolside: Laguna M.1 (free)" },
    { id: "~anthropic/claude-haiku-latest", name: "Anthropic Claude Haiku Latest" },
    { id: "~openai/gpt-mini-latest", name: "OpenAI GPT Mini Latest" },
    { id: "~google/gemini-pro-latest", name: "Google Gemini Pro Latest" },
    { id: "~moonshotai/kimi-latest", name: "MoonshotAI Kimi Latest" },
    { id: "~google/gemini-flash-latest", name: "Google Gemini Flash Latest" },
    { id: "~anthropic/claude-sonnet-latest", name: "Anthropic Claude Sonnet Latest" },
    { id: "~openai/gpt-latest", name: "OpenAI GPT Latest" },
    { id: "qwen/qwen3.5-plus-20260420", name: "Qwen: Qwen3.5 Plus 2026-04-20" },
    { id: "qwen/qwen3.6-flash", name: "Qwen: Qwen3.6 Flash" },
    { id: "qwen/qwen3.6-35b-a3b", name: "Qwen: Qwen3.6 35B A3B" },
    { id: "qwen/qwen3.6-max-preview", name: "Qwen: Qwen3.6 Max Preview" },
    { id: "qwen/qwen3.6-27b", name: "Qwen: Qwen3.6 27B" },
    { id: "openai/gpt-5.5-pro", name: "OpenAI: GPT-5.5 Pro" },
    { id: "openai/gpt-5.5", name: "OpenAI: GPT-5.5" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek: DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek: DeepSeek V4 Flash" },
    { id: "inclusionai/ling-2.6-1t", name: "inclusionAI: Ling-2.6-1T" },
    { id: "tencent/hy3-preview", name: "Tencent: Hy3 preview" },
    { id: "xiaomi/mimo-v2.5-pro", name: "Xiaomi: MiMo-V2.5-Pro" },
    { id: "xiaomi/mimo-v2.5", name: "Xiaomi: MiMo-V2.5" },
    { id: "openai/gpt-5.4-image-2", name: "OpenAI: GPT-5.4 Image 2" },
    { id: "inclusionai/ling-2.6-flash", name: "inclusionAI: Ling-2.6-flash" },
    { id: "~anthropic/claude-opus-latest", name: "Anthropic: Claude Opus Latest" },
    { id: "openrouter/pareto-code", name: "Pareto Code Router" },
    { id: "moonshotai/kimi-k2.6:free", name: "MoonshotAI: Kimi K2.6 (free)" },
    { id: "moonshotai/kimi-k2.6", name: "MoonshotAI: Kimi K2.6" },
    { id: "anthropic/claude-opus-4.7", name: "Anthropic: Claude Opus 4.7" },
    { id: "anthropic/claude-opus-4.6-fast", name: "Anthropic: Claude Opus 4.6 (Fast)" },
    { id: "z-ai/glm-5.1", name: "Z.ai: GLM 5.1" },
    { id: "google/gemma-4-26b-a4b-it:free", name: "Google: Gemma 4 26B A4B  (free)" },
    { id: "google/gemma-4-26b-a4b-it", name: "Google: Gemma 4 26B A4B " },
    { id: "google/gemma-4-31b-it:free", name: "Google: Gemma 4 31B (free)" },
    { id: "google/gemma-4-31b-it", name: "Google: Gemma 4 31B" },
    { id: "qwen/qwen3.6-plus", name: "Qwen: Qwen3.6 Plus" },
    { id: "z-ai/glm-5v-turbo", name: "Z.ai: GLM 5V Turbo" },
    { id: "arcee-ai/trinity-large-thinking", name: "Arcee AI: Trinity Large Thinking" },
    { id: "x-ai/grok-4.20-multi-agent", name: "xAI: Grok 4.20 Multi-Agent" },
    { id: "x-ai/grok-4.20", name: "xAI: Grok 4.20" },
    { id: "google/lyria-3-pro-preview", name: "Google: Lyria 3 Pro Preview" },
    { id: "google/lyria-3-clip-preview", name: "Google: Lyria 3 Clip Preview" },
    { id: "kwaipilot/kat-coder-pro-v2", name: "Kwaipilot: KAT-Coder-Pro V2" },
    { id: "rekaai/reka-edge", name: "Reka Edge" },
    { id: "minimax/minimax-m2.7", name: "MiniMax: MiniMax M2.7" },
    { id: "openai/gpt-5.4-nano", name: "OpenAI: GPT-5.4 Nano" },
    { id: "openai/gpt-5.4-mini", name: "OpenAI: GPT-5.4 Mini" },
    { id: "mistralai/mistral-small-2603", name: "Mistral: Mistral Small 4" },
    { id: "z-ai/glm-5-turbo", name: "Z.ai: GLM 5 Turbo" },
    { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "NVIDIA: Nemotron 3 Super (free)" },
    { id: "nvidia/nemotron-3-super-120b-a12b", name: "NVIDIA: Nemotron 3 Super" },
    { id: "bytedance-seed/seed-2.0-lite", name: "ByteDance Seed: Seed-2.0-Lite" },
    { id: "qwen/qwen3.5-9b", name: "Qwen: Qwen3.5-9B" },
    { id: "openai/gpt-5.4-pro", name: "OpenAI: GPT-5.4 Pro" },
    { id: "openai/gpt-5.4", name: "OpenAI: GPT-5.4" },
    { id: "inception/mercury-2", name: "Inception: Mercury 2" },
    { id: "openai/gpt-5.3-chat", name: "OpenAI: GPT-5.3 Chat" },
    { id: "google/gemini-3.1-flash-lite-preview", name: "Google: Gemini 3.1 Flash Lite Preview" },
    { id: "bytedance-seed/seed-2.0-mini", name: "ByteDance Seed: Seed-2.0-Mini" },
    { id: "google/gemini-3.1-flash-image-preview", name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)" },
    { id: "qwen/qwen3.5-35b-a3b", name: "Qwen: Qwen3.5-35B-A3B" },
    { id: "qwen/qwen3.5-27b", name: "Qwen: Qwen3.5-27B" },
    { id: "qwen/qwen3.5-122b-a10b", name: "Qwen: Qwen3.5-122B-A10B" },
    { id: "qwen/qwen3.5-flash-02-23", name: "Qwen: Qwen3.5-Flash" },
    { id: "liquid/lfm-2-24b-a2b", name: "LiquidAI: LFM2-24B-A2B" },
    { id: "google/gemini-3.1-pro-preview-customtools", name: "Google: Gemini 3.1 Pro Preview Custom Tools" },
    { id: "openai/gpt-5.3-codex", name: "OpenAI: GPT-5.3-Codex" },
    { id: "aion-labs/aion-2.0", name: "AionLabs: Aion-2.0" },
    { id: "google/gemini-3.1-pro-preview", name: "Google: Gemini 3.1 Pro Preview" },
    { id: "anthropic/claude-sonnet-4.6", name: "Anthropic: Claude Sonnet 4.6" },
    { id: "qwen/qwen3.5-plus-02-15", name: "Qwen: Qwen3.5 Plus 2026-02-15" },
    { id: "qwen/qwen3.5-397b-a17b", name: "Qwen: Qwen3.5 397B A17B" },
    { id: "minimax/minimax-m2.5", name: "MiniMax: MiniMax M2.5" },
    { id: "z-ai/glm-5", name: "Z.ai: GLM 5" },
    { id: "qwen/qwen3-max-thinking", name: "Qwen: Qwen3 Max Thinking" },
    { id: "anthropic/claude-opus-4.6", name: "Anthropic: Claude Opus 4.6" },
    { id: "qwen/qwen3-coder-next", name: "Qwen: Qwen3 Coder Next" },
    { id: "openrouter/free", name: "Free Models Router" },
    { id: "stepfun/step-3.5-flash", name: "StepFun: Step 3.5 Flash" },
    { id: "moonshotai/kimi-k2.5", name: "MoonshotAI: Kimi K2.5" },
    { id: "upstage/solar-pro-3", name: "Upstage: Solar Pro 3" },
    { id: "minimax/minimax-m2-her", name: "MiniMax: MiniMax M2-her" },
    { id: "writer/palmyra-x5", name: "Writer: Palmyra X5" },
    { id: "liquid/lfm-2.5-1.2b-thinking:free", name: "LiquidAI: LFM2.5-1.2B-Thinking (free)" },
    { id: "liquid/lfm-2.5-1.2b-instruct:free", name: "LiquidAI: LFM2.5-1.2B-Instruct (free)" },
    { id: "openai/gpt-audio", name: "OpenAI: GPT Audio" },
    { id: "openai/gpt-audio-mini", name: "OpenAI: GPT Audio Mini" },
    { id: "z-ai/glm-4.7-flash", name: "Z.ai: GLM 4.7 Flash" },
    { id: "openai/gpt-5.2-codex", name: "OpenAI: GPT-5.2-Codex" },
    { id: "bytedance-seed/seed-1.6-flash", name: "ByteDance Seed: Seed 1.6 Flash" },
    { id: "bytedance-seed/seed-1.6", name: "ByteDance Seed: Seed 1.6" },
    { id: "minimax/minimax-m2.1", name: "MiniMax: MiniMax M2.1" },
    { id: "z-ai/glm-4.7", name: "Z.ai: GLM 4.7" },
    { id: "google/gemini-3-flash-preview", name: "Google: Gemini 3 Flash Preview" },
    { id: "xiaomi/mimo-v2-flash", name: "Xiaomi: MiMo-V2-Flash" },
    { id: "nvidia/nemotron-3-nano-30b-a3b:free", name: "NVIDIA: Nemotron 3 Nano 30B A3B (free)" },
    { id: "nvidia/nemotron-3-nano-30b-a3b", name: "NVIDIA: Nemotron 3 Nano 30B A3B" },
    { id: "openai/gpt-5.2-chat", name: "OpenAI: GPT-5.2 Chat" },
    { id: "openai/gpt-5.2-pro", name: "OpenAI: GPT-5.2 Pro" },
    { id: "openai/gpt-5.2", name: "OpenAI: GPT-5.2" },
    { id: "mistralai/devstral-2512", name: "Mistral: Devstral 2 2512" },
    { id: "relace/relace-search", name: "Relace: Relace Search" },
    { id: "z-ai/glm-4.6v", name: "Z.ai: GLM 4.6V" },
    { id: "nex-agi/deepseek-v3.1-nex-n1", name: "Nex AGI: DeepSeek V3.1 Nex N1" },
    { id: "essentialai/rnj-1-instruct", name: "EssentialAI: Rnj 1 Instruct" },
    { id: "openrouter/bodybuilder", name: "Body Builder (beta)" },
    { id: "openai/gpt-5.1-codex-max", name: "OpenAI: GPT-5.1-Codex-Max" },
    { id: "amazon/nova-2-lite-v1", name: "Amazon: Nova 2 Lite" },
    { id: "mistralai/ministral-14b-2512", name: "Mistral: Ministral 3 14B 2512" },
    { id: "mistralai/ministral-8b-2512", name: "Mistral: Ministral 3 8B 2512" },
    { id: "mistralai/ministral-3b-2512", name: "Mistral: Ministral 3 3B 2512" },
    { id: "mistralai/mistral-large-2512", name: "Mistral: Mistral Large 3 2512" },
    { id: "arcee-ai/trinity-mini", name: "Arcee AI: Trinity Mini" },
    { id: "deepseek/deepseek-v3.2", name: "DeepSeek: DeepSeek V3.2" },
    { id: "prime-intellect/intellect-3", name: "Prime Intellect: INTELLECT-3" },
    { id: "anthropic/claude-opus-4.5", name: "Anthropic: Claude Opus 4.5" },
    { id: "allenai/olmo-3-32b-think", name: "AllenAI: Olmo 3 32B Think" },
    { id: "google/gemini-3-pro-image-preview", name: "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)" },
    { id: "deepcogito/cogito-v2.1-671b", name: "Deep Cogito: Cogito v2.1 671B" },
    { id: "openai/gpt-5.1", name: "OpenAI: GPT-5.1" },
    { id: "openai/gpt-5.1-chat", name: "OpenAI: GPT-5.1 Chat" },
    { id: "openai/gpt-5.1-codex", name: "OpenAI: GPT-5.1-Codex" },
    { id: "openai/gpt-5.1-codex-mini", name: "OpenAI: GPT-5.1-Codex-Mini" },
    { id: "moonshotai/kimi-k2-thinking", name: "MoonshotAI: Kimi K2 Thinking" },
    { id: "amazon/nova-premier-v1", name: "Amazon: Nova Premier 1.0" },
    { id: "perplexity/sonar-pro-search", name: "Perplexity: Sonar Pro Search" },
    { id: "mistralai/voxtral-small-24b-2507", name: "Mistral: Voxtral Small 24B 2507" },
    { id: "openai/gpt-oss-safeguard-20b", name: "OpenAI: gpt-oss-safeguard-20b" },
    { id: "nvidia/nemotron-nano-12b-v2-vl:free", name: "NVIDIA: Nemotron Nano 12B 2 VL (free)" },
    { id: "minimax/minimax-m2", name: "MiniMax: MiniMax M2" },
    { id: "qwen/qwen3-vl-32b-instruct", name: "Qwen: Qwen3 VL 32B Instruct" },
    { id: "ibm-granite/granite-4.0-h-micro", name: "IBM: Granite 4.0 Micro" },
    { id: "microsoft/phi-4-mini-instruct", name: "Microsoft: Phi 4 Mini Instruct" },
    { id: "openai/gpt-5-image-mini", name: "OpenAI: GPT-5 Image Mini" },
    { id: "anthropic/claude-haiku-4.5", name: "Anthropic: Claude Haiku 4.5" },
    { id: "qwen/qwen3-vl-8b-thinking", name: "Qwen: Qwen3 VL 8B Thinking" },
    { id: "qwen/qwen3-vl-8b-instruct", name: "Qwen: Qwen3 VL 8B Instruct" },
    { id: "openai/gpt-5-image", name: "OpenAI: GPT-5 Image" },
    { id: "openai/o3-deep-research", name: "OpenAI: o3 Deep Research" },
    { id: "openai/o4-mini-deep-research", name: "OpenAI: o4 Mini Deep Research" },
    { id: "nvidia/llama-3.3-nemotron-super-49b-v1.5", name: "NVIDIA: Llama 3.3 Nemotron Super 49B V1.5" },
    { id: "google/gemini-2.5-flash-image", name: "Google: Nano Banana (Gemini 2.5 Flash Image)" },
    { id: "qwen/qwen3-vl-30b-a3b-thinking", name: "Qwen: Qwen3 VL 30B A3B Thinking" },
    { id: "qwen/qwen3-vl-30b-a3b-instruct", name: "Qwen: Qwen3 VL 30B A3B Instruct" },
    { id: "openai/gpt-5-pro", name: "OpenAI: GPT-5 Pro" },
    { id: "z-ai/glm-4.6", name: "Z.ai: GLM 4.6" },
    { id: "anthropic/claude-sonnet-4.5", name: "Anthropic: Claude Sonnet 4.5" },
    { id: "deepseek/deepseek-v3.2-exp", name: "DeepSeek: DeepSeek V3.2 Exp" },
    { id: "thedrummer/cydonia-24b-v4.1", name: "TheDrummer: Cydonia 24B V4.1" },
    { id: "relace/relace-apply-3", name: "Relace: Relace Apply 3" },
    { id: "google/gemini-2.5-flash-lite-preview-09-2025", name: "Google: Gemini 2.5 Flash Lite Preview 09-2025" },
    { id: "qwen/qwen3-vl-235b-a22b-thinking", name: "Qwen: Qwen3 VL 235B A22B Thinking" },
    { id: "qwen/qwen3-vl-235b-a22b-instruct", name: "Qwen: Qwen3 VL 235B A22B Instruct" },
    { id: "qwen/qwen3-max", name: "Qwen: Qwen3 Max" },
    { id: "qwen/qwen3-coder-plus", name: "Qwen: Qwen3 Coder Plus" },
    { id: "openai/gpt-5-codex", name: "OpenAI: GPT-5 Codex" },
    { id: "deepseek/deepseek-v3.1-terminus", name: "DeepSeek: DeepSeek V3.1 Terminus" },
    { id: "qwen/qwen3-coder-flash", name: "Qwen: Qwen3 Coder Flash" },
    { id: "qwen/qwen3-next-80b-a3b-thinking", name: "Qwen: Qwen3 Next 80B A3B Thinking" },
    { id: "qwen/qwen3-next-80b-a3b-instruct:free", name: "Qwen: Qwen3 Next 80B A3B Instruct (free)" },
    { id: "qwen/qwen3-next-80b-a3b-instruct", name: "Qwen: Qwen3 Next 80B A3B Instruct" },
    { id: "qwen/qwen-plus-2025-07-28:thinking", name: "Qwen: Qwen Plus 0728 (thinking)" },
    { id: "qwen/qwen-plus-2025-07-28", name: "Qwen: Qwen Plus 0728" },
    { id: "nvidia/nemotron-nano-9b-v2:free", name: "NVIDIA: Nemotron Nano 9B V2 (free)" },
    { id: "nvidia/nemotron-nano-9b-v2", name: "NVIDIA: Nemotron Nano 9B V2" },
    { id: "moonshotai/kimi-k2-0905", name: "MoonshotAI: Kimi K2 0905" },
    { id: "qwen/qwen3-30b-a3b-thinking-2507", name: "Qwen: Qwen3 30B A3B Thinking 2507" },
    { id: "nousresearch/hermes-4-70b", name: "Nous: Hermes 4 70B" },
    { id: "nousresearch/hermes-4-405b", name: "Nous: Hermes 4 405B" },
    { id: "deepseek/deepseek-chat-v3.1", name: "DeepSeek: DeepSeek V3.1" },
    { id: "mistralai/mistral-medium-3.1", name: "Mistral: Mistral Medium 3.1" },
    { id: "baidu/ernie-4.5-vl-28b-a3b", name: "Baidu: ERNIE 4.5 VL 28B A3B" },
    { id: "z-ai/glm-4.5v", name: "Z.ai: GLM 4.5V" },
    { id: "ai21/jamba-large-1.7", name: "AI21: Jamba Large 1.7" },
    { id: "openai/gpt-5-chat", name: "OpenAI: GPT-5 Chat" },
    { id: "openai/gpt-5", name: "OpenAI: GPT-5" },
    { id: "openai/gpt-5-mini", name: "OpenAI: GPT-5 Mini" },
    { id: "openai/gpt-5-nano", name: "OpenAI: GPT-5 Nano" },
    { id: "openai/gpt-oss-120b:free", name: "OpenAI: gpt-oss-120b (free)" },
    { id: "openai/gpt-oss-120b", name: "OpenAI: gpt-oss-120b" },
    { id: "openai/gpt-oss-20b:free", name: "OpenAI: gpt-oss-20b (free)" },
    { id: "openai/gpt-oss-20b", name: "OpenAI: gpt-oss-20b" },
    { id: "anthropic/claude-opus-4.1", name: "Anthropic: Claude Opus 4.1" },
    { id: "mistralai/codestral-2508", name: "Mistral: Codestral 2508" },
    { id: "qwen/qwen3-coder-30b-a3b-instruct", name: "Qwen: Qwen3 Coder 30B A3B Instruct" },
    { id: "qwen/qwen3-30b-a3b-instruct-2507", name: "Qwen: Qwen3 30B A3B Instruct 2507" },
    { id: "z-ai/glm-4.5", name: "Z.ai: GLM 4.5" },
    { id: "z-ai/glm-4.5-air:free", name: "Z.ai: GLM 4.5 Air (free)" },
    { id: "z-ai/glm-4.5-air", name: "Z.ai: GLM 4.5 Air" },
    { id: "qwen/qwen3-235b-a22b-thinking-2507", name: "Qwen: Qwen3 235B A22B Thinking 2507" },
    { id: "z-ai/glm-4-32b", name: "Z.ai: GLM 4 32B " },
    { id: "qwen/qwen3-coder:free", name: "Qwen: Qwen3 Coder 480B A35B (free)" },
    { id: "qwen/qwen3-coder", name: "Qwen: Qwen3 Coder 480B A35B" },
    { id: "bytedance/ui-tars-1.5-7b", name: "ByteDance: UI-TARS 7B " },
    { id: "google/gemini-2.5-flash-lite", name: "Google: Gemini 2.5 Flash Lite" },
    { id: "qwen/qwen3-235b-a22b-2507", name: "Qwen: Qwen3 235B A22B Instruct 2507" },
    { id: "switchpoint/router", name: "Switchpoint Router" },
    { id: "moonshotai/kimi-k2", name: "MoonshotAI: Kimi K2 0711" },
    { id: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free", name: "Venice: Uncensored (free)" },
    { id: "tencent/hunyuan-a13b-instruct", name: "Tencent: Hunyuan A13B Instruct" },
    { id: "morph/morph-v3-large", name: "Morph: Morph V3 Large" },
    { id: "morph/morph-v3-fast", name: "Morph: Morph V3 Fast" },
    { id: "baidu/ernie-4.5-vl-424b-a47b", name: "Baidu: ERNIE 4.5 VL 424B A47B " },
    { id: "baidu/ernie-4.5-300b-a47b", name: "Baidu: ERNIE 4.5 300B A47B " },
    { id: "mistralai/mistral-small-3.2-24b-instruct", name: "Mistral: Mistral Small 3.2 24B" },
    { id: "minimax/minimax-m1", name: "MiniMax: MiniMax M1" },
    { id: "google/gemini-2.5-flash", name: "Google: Gemini 2.5 Flash" },
    { id: "google/gemini-2.5-pro", name: "Google: Gemini 2.5 Pro" },
    { id: "openai/o3-pro", name: "OpenAI: o3 Pro" },
    { id: "google/gemini-2.5-pro-preview", name: "Google: Gemini 2.5 Pro Preview 06-05" },
    { id: "deepseek/deepseek-r1-0528", name: "DeepSeek: R1 0528" },
    { id: "anthropic/claude-opus-4", name: "Anthropic: Claude Opus 4" },
    { id: "anthropic/claude-sonnet-4", name: "Anthropic: Claude Sonnet 4" },
    { id: "google/gemma-3n-e4b-it", name: "Google: Gemma 3n 4B" },
    { id: "mistralai/mistral-medium-3", name: "Mistral: Mistral Medium 3" },
    { id: "google/gemini-2.5-pro-preview-05-06", name: "Google: Gemini 2.5 Pro Preview 05-06" },
    { id: "arcee-ai/spotlight", name: "Arcee AI: Spotlight" },
    { id: "arcee-ai/maestro-reasoning", name: "Arcee AI: Maestro Reasoning" },
    { id: "arcee-ai/virtuoso-large", name: "Arcee AI: Virtuoso Large" },
    { id: "arcee-ai/coder-large", name: "Arcee AI: Coder Large" },
    { id: "meta-llama/llama-guard-4-12b", name: "Meta: Llama Guard 4 12B" },
    { id: "qwen/qwen3-30b-a3b", name: "Qwen: Qwen3 30B A3B" },
    { id: "qwen/qwen3-8b", name: "Qwen: Qwen3 8B" },
    { id: "qwen/qwen3-14b", name: "Qwen: Qwen3 14B" },
    { id: "qwen/qwen3-32b", name: "Qwen: Qwen3 32B" },
    { id: "qwen/qwen3-235b-a22b", name: "Qwen: Qwen3 235B A22B" },
    { id: "openai/o4-mini-high", name: "OpenAI: o4 Mini High" },
    { id: "openai/o3", name: "OpenAI: o3" },
    { id: "openai/o4-mini", name: "OpenAI: o4 Mini" },
    { id: "openai/gpt-4.1", name: "OpenAI: GPT-4.1" },
    { id: "openai/gpt-4.1-mini", name: "OpenAI: GPT-4.1 Mini" },
    { id: "openai/gpt-4.1-nano", name: "OpenAI: GPT-4.1 Nano" },
    { id: "meta-llama/llama-4-maverick", name: "Meta: Llama 4 Maverick" },
    { id: "meta-llama/llama-4-scout", name: "Meta: Llama 4 Scout" },
    { id: "deepseek/deepseek-chat-v3-0324", name: "DeepSeek: DeepSeek V3 0324" },
    { id: "openai/o1-pro", name: "OpenAI: o1-pro" },
    { id: "mistralai/mistral-small-3.1-24b-instruct", name: "Mistral: Mistral Small 3.1 24B" },
    { id: "google/gemma-3-4b-it", name: "Google: Gemma 3 4B" },
    { id: "google/gemma-3-12b-it", name: "Google: Gemma 3 12B" },
    { id: "cohere/command-a", name: "Cohere: Command A" },
    { id: "openai/gpt-4o-mini-search-preview", name: "OpenAI: GPT-4o-mini Search Preview" },
    { id: "openai/gpt-4o-search-preview", name: "OpenAI: GPT-4o Search Preview" },
    { id: "rekaai/reka-flash-3", name: "Reka Flash 3" },
    { id: "google/gemma-3-27b-it", name: "Google: Gemma 3 27B" },
    { id: "thedrummer/skyfall-36b-v2", name: "TheDrummer: Skyfall 36B V2" },
    { id: "perplexity/sonar-reasoning-pro", name: "Perplexity: Sonar Reasoning Pro" },
    { id: "perplexity/sonar-pro", name: "Perplexity: Sonar Pro" },
    { id: "perplexity/sonar-deep-research", name: "Perplexity: Sonar Deep Research" },
    { id: "mistralai/mistral-saba", name: "Mistral: Saba" },
    { id: "meta-llama/llama-guard-3-8b", name: "Llama Guard 3 8B" },
    { id: "openai/o3-mini-high", name: "OpenAI: o3 Mini High" },
    { id: "aion-labs/aion-1.0", name: "AionLabs: Aion-1.0" },
    { id: "aion-labs/aion-1.0-mini", name: "AionLabs: Aion-1.0-Mini" },
    { id: "aion-labs/aion-rp-llama-3.1-8b", name: "AionLabs: Aion-RP 1.0 (8B)" },
    { id: "qwen/qwen2.5-vl-72b-instruct", name: "Qwen: Qwen2.5 VL 72B Instruct" },
    { id: "qwen/qwen-plus", name: "Qwen: Qwen-Plus" },
    { id: "openai/o3-mini", name: "OpenAI: o3 Mini" },
    { id: "mistralai/mistral-small-24b-instruct-2501", name: "Mistral: Mistral Small 3" },
    { id: "deepseek/deepseek-r1-distill-qwen-32b", name: "DeepSeek: R1 Distill Qwen 32B" },
    { id: "perplexity/sonar", name: "Perplexity: Sonar" },
    { id: "deepseek/deepseek-r1-distill-llama-70b", name: "DeepSeek: R1 Distill Llama 70B" },
    { id: "deepseek/deepseek-r1", name: "DeepSeek: R1" },
    { id: "minimax/minimax-01", name: "MiniMax: MiniMax-01" },
    { id: "microsoft/phi-4", name: "Microsoft: Phi 4" },
    { id: "sao10k/l3.1-70b-hanami-x1", name: "Sao10K: Llama 3.1 70B Hanami x1" },
    { id: "deepseek/deepseek-chat", name: "DeepSeek: DeepSeek V3" },
    { id: "sao10k/l3.3-euryale-70b", name: "Sao10K: Llama 3.3 Euryale 70B" },
    { id: "openai/o1", name: "OpenAI: o1" },
    { id: "cohere/command-r7b-12-2024", name: "Cohere: Command R7B (12-2024)" },
    { id: "meta-llama/llama-3.3-70b-instruct:free", name: "Meta: Llama 3.3 70B Instruct (free)" },
    { id: "meta-llama/llama-3.3-70b-instruct", name: "Meta: Llama 3.3 70B Instruct" },
    { id: "amazon/nova-lite-v1", name: "Amazon: Nova Lite 1.0" },
    { id: "amazon/nova-micro-v1", name: "Amazon: Nova Micro 1.0" },
    { id: "amazon/nova-pro-v1", name: "Amazon: Nova Pro 1.0" },
    { id: "openai/gpt-4o-2024-11-20", name: "OpenAI: GPT-4o (2024-11-20)" },
    { id: "mistralai/mistral-large-2407", name: "Mistral Large 2407" },
    { id: "qwen/qwen-2.5-coder-32b-instruct", name: "Qwen2.5 Coder 32B Instruct" },
    { id: "thedrummer/unslopnemo-12b", name: "TheDrummer: UnslopNemo 12B" },
    { id: "anthropic/claude-3.5-haiku", name: "Anthropic: Claude 3.5 Haiku" },
    { id: "anthracite-org/magnum-v4-72b", name: "Magnum v4 72B" },
    { id: "qwen/qwen-2.5-7b-instruct", name: "Qwen: Qwen2.5 7B Instruct" },
    { id: "inflection/inflection-3-pi", name: "Inflection: Inflection 3 Pi" },
    { id: "inflection/inflection-3-productivity", name: "Inflection: Inflection 3 Productivity" },
    { id: "thedrummer/rocinante-12b", name: "TheDrummer: Rocinante 12B" },
    { id: "meta-llama/llama-3.2-1b-instruct", name: "Meta: Llama 3.2 1B Instruct" },
    { id: "meta-llama/llama-3.2-11b-vision-instruct", name: "Meta: Llama 3.2 11B Vision Instruct" },
    { id: "meta-llama/llama-3.2-3b-instruct:free", name: "Meta: Llama 3.2 3B Instruct (free)" },
    { id: "meta-llama/llama-3.2-3b-instruct", name: "Meta: Llama 3.2 3B Instruct" },
    { id: "qwen/qwen-2.5-72b-instruct", name: "Qwen2.5 72B Instruct" },
    { id: "cohere/command-r-08-2024", name: "Cohere: Command R (08-2024)" },
    { id: "cohere/command-r-plus-08-2024", name: "Cohere: Command R+ (08-2024)" },
    { id: "sao10k/l3.1-euryale-70b", name: "Sao10K: Llama 3.1 Euryale 70B v2.2" },
    { id: "nousresearch/hermes-3-llama-3.1-70b", name: "Nous: Hermes 3 70B Instruct" },
    { id: "nousresearch/hermes-3-llama-3.1-405b:free", name: "Nous: Hermes 3 405B Instruct (free)" },
    { id: "nousresearch/hermes-3-llama-3.1-405b", name: "Nous: Hermes 3 405B Instruct" },
    { id: "sao10k/l3-lunaris-8b", name: "Sao10K: Llama 3 8B Lunaris" },
    { id: "openai/gpt-4o-2024-08-06", name: "OpenAI: GPT-4o (2024-08-06)" },
    { id: "meta-llama/llama-3.1-8b-instruct", name: "Meta: Llama 3.1 8B Instruct" },
    { id: "meta-llama/llama-3.1-70b-instruct", name: "Meta: Llama 3.1 70B Instruct" },
    { id: "mistralai/mistral-nemo", name: "Mistral: Mistral Nemo" },
    { id: "openai/gpt-4o-mini", name: "OpenAI: GPT-4o-mini" },
    { id: "openai/gpt-4o-mini-2024-07-18", name: "OpenAI: GPT-4o-mini (2024-07-18)" },
    { id: "google/gemma-2-27b-it", name: "Google: Gemma 2 27B" },
    { id: "sao10k/l3-euryale-70b", name: "Sao10k: Llama 3 Euryale 70B v2.1" },
    { id: "nousresearch/hermes-2-pro-llama-3-8b", name: "NousResearch: Hermes 2 Pro - Llama-3 8B" },
    { id: "openai/gpt-4o", name: "OpenAI: GPT-4o" },
    { id: "openai/gpt-4o-2024-05-13", name: "OpenAI: GPT-4o (2024-05-13)" },
    { id: "meta-llama/llama-3-8b-instruct", name: "Meta: Llama 3 8B Instruct" },
    { id: "meta-llama/llama-3-70b-instruct", name: "Meta: Llama 3 70B Instruct" },
    { id: "mistralai/mixtral-8x22b-instruct", name: "Mistral: Mixtral 8x22B Instruct" },
    { id: "microsoft/wizardlm-2-8x22b", name: "WizardLM-2 8x22B" },
    { id: "openai/gpt-4-turbo", name: "OpenAI: GPT-4 Turbo" },
    { id: "anthropic/claude-3-haiku", name: "Anthropic: Claude 3 Haiku" },
    { id: "mistralai/mistral-large", name: "Mistral Large" },
    { id: "openai/gpt-4-turbo-preview", name: "OpenAI: GPT-4 Turbo Preview" },
    { id: "openai/gpt-3.5-turbo-0613", name: "OpenAI: GPT-3.5 Turbo (older v0613)" },
    { id: "openrouter/auto", name: "Auto Router" },
    { id: "openai/gpt-4-1106-preview", name: "OpenAI: GPT-4 Turbo (older v1106)" },
    { id: "openai/gpt-3.5-turbo-instruct", name: "OpenAI: GPT-3.5 Turbo Instruct" },
    { id: "openai/gpt-3.5-turbo-16k", name: "OpenAI: GPT-3.5 Turbo 16k" },
    { id: "mancer/weaver", name: "Mancer: Weaver (alpha)" },
    { id: "undi95/remm-slerp-l2-13b", name: "ReMM SLERP 13B" },
    { id: "gryphe/mythomax-l2-13b", name: "MythoMax 13B" },
    { id: "openai/gpt-3.5-turbo", name: "OpenAI: GPT-3.5 Turbo" },
    { id: "openai/gpt-4", name: "OpenAI: GPT-4" },
    { id: "openai/gpt-4-0314", name: "OpenAI: GPT-4 (older v0314)" },
  ],
  "gitlawb-mimo": [
    { id: "minimax/minimax-m3", name: "MiniMax: MiniMax M3" },
    { id: "stepfun/step-3.7-flash", name: "StepFun: Step 3.7 Flash" },
    { id: "anthropic/claude-opus-4.8-fast", name: "Anthropic: Claude Opus 4.8 (Fast)" },
    { id: "anthropic/claude-opus-4.8", name: "Anthropic: Claude Opus 4.8" },
    { id: "qwen/qwen3.7-max", name: "Qwen: Qwen3.7 Max" },
    { id: "x-ai/grok-build-0.1", name: "xAI: Grok Build 0.1" },
    { id: "google/gemini-3.5-flash", name: "Google: Gemini 3.5 Flash" },
    { id: "anthropic/claude-opus-4.7-fast", name: "Anthropic: Claude Opus 4.7 (Fast)" },
    { id: "perceptron/perceptron-mk1", name: "Perceptron: Perceptron Mk1" },
    { id: "inclusionai/ring-2.6-1t", name: "inclusionAI: Ring-2.6-1T" },
    { id: "google/gemini-3.1-flash-lite", name: "Google: Gemini 3.1 Flash Lite" },
    { id: "openai/gpt-chat-latest", name: "OpenAI: GPT Chat Latest" },
    { id: "x-ai/grok-4.3", name: "xAI: Grok 4.3" },
    { id: "ibm-granite/granite-4.1-8b", name: "IBM: Granite 4.1 8B" },
    { id: "mistralai/mistral-medium-3-5", name: "Mistral: Mistral Medium 3.5" },
    { id: "openrouter/owl-alpha", name: "Owl Alpha" },
    { id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free", name: "NVIDIA: Nemotron 3 Nano Omni (free)" },
    { id: "poolside/laguna-xs.2:free", name: "Poolside: Laguna XS.2 (free)" },
    { id: "poolside/laguna-m.1:free", name: "Poolside: Laguna M.1 (free)" },
    { id: "~anthropic/claude-haiku-latest", name: "Anthropic Claude Haiku Latest" },
    { id: "~openai/gpt-mini-latest", name: "OpenAI GPT Mini Latest" },
    { id: "~google/gemini-pro-latest", name: "Google Gemini Pro Latest" },
    { id: "~moonshotai/kimi-latest", name: "MoonshotAI Kimi Latest" },
    { id: "~google/gemini-flash-latest", name: "Google Gemini Flash Latest" },
    { id: "~anthropic/claude-sonnet-latest", name: "Anthropic Claude Sonnet Latest" },
    { id: "~openai/gpt-latest", name: "OpenAI GPT Latest" },
    { id: "qwen/qwen3.5-plus-20260420", name: "Qwen: Qwen3.5 Plus 2026-04-20" },
    { id: "qwen/qwen3.6-flash", name: "Qwen: Qwen3.6 Flash" },
    { id: "qwen/qwen3.6-35b-a3b", name: "Qwen: Qwen3.6 35B A3B" },
    { id: "qwen/qwen3.6-max-preview", name: "Qwen: Qwen3.6 Max Preview" },
    { id: "qwen/qwen3.6-27b", name: "Qwen: Qwen3.6 27B" },
    { id: "openai/gpt-5.5-pro", name: "OpenAI: GPT-5.5 Pro" },
    { id: "openai/gpt-5.5", name: "OpenAI: GPT-5.5" },
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek: DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek: DeepSeek V4 Flash" },
    { id: "inclusionai/ling-2.6-1t", name: "inclusionAI: Ling-2.6-1T" },
    { id: "tencent/hy3-preview", name: "Tencent: Hy3 preview" },
    { id: "xiaomi/mimo-v2.5-pro", name: "Xiaomi: MiMo-V2.5-Pro" },
    { id: "xiaomi/mimo-v2.5", name: "Xiaomi: MiMo-V2.5" },
    { id: "openai/gpt-5.4-image-2", name: "OpenAI: GPT-5.4 Image 2" },
    { id: "inclusionai/ling-2.6-flash", name: "inclusionAI: Ling-2.6-flash" },
    { id: "~anthropic/claude-opus-latest", name: "Anthropic: Claude Opus Latest" },
    { id: "openrouter/pareto-code", name: "Pareto Code Router" },
    { id: "moonshotai/kimi-k2.6:free", name: "MoonshotAI: Kimi K2.6 (free)" },
    { id: "moonshotai/kimi-k2.6", name: "MoonshotAI: Kimi K2.6" },
    { id: "anthropic/claude-opus-4.7", name: "Anthropic: Claude Opus 4.7" },
    { id: "anthropic/claude-opus-4.6-fast", name: "Anthropic: Claude Opus 4.6 (Fast)" },
    { id: "z-ai/glm-5.1", name: "Z.ai: GLM 5.1" },
    { id: "google/gemma-4-26b-a4b-it:free", name: "Google: Gemma 4 26B A4B  (free)" },
    { id: "google/gemma-4-26b-a4b-it", name: "Google: Gemma 4 26B A4B " },
    { id: "google/gemma-4-31b-it:free", name: "Google: Gemma 4 31B (free)" },
    { id: "google/gemma-4-31b-it", name: "Google: Gemma 4 31B" },
    { id: "qwen/qwen3.6-plus", name: "Qwen: Qwen3.6 Plus" },
    { id: "z-ai/glm-5v-turbo", name: "Z.ai: GLM 5V Turbo" },
    { id: "arcee-ai/trinity-large-thinking", name: "Arcee AI: Trinity Large Thinking" },
    { id: "x-ai/grok-4.20-multi-agent", name: "xAI: Grok 4.20 Multi-Agent" },
    { id: "x-ai/grok-4.20", name: "xAI: Grok 4.20" },
    { id: "google/lyria-3-pro-preview", name: "Google: Lyria 3 Pro Preview" },
    { id: "google/lyria-3-clip-preview", name: "Google: Lyria 3 Clip Preview" },
    { id: "kwaipilot/kat-coder-pro-v2", name: "Kwaipilot: KAT-Coder-Pro V2" },
    { id: "rekaai/reka-edge", name: "Reka Edge" },
    { id: "minimax/minimax-m2.7", name: "MiniMax: MiniMax M2.7" },
    { id: "openai/gpt-5.4-nano", name: "OpenAI: GPT-5.4 Nano" },
    { id: "openai/gpt-5.4-mini", name: "OpenAI: GPT-5.4 Mini" },
    { id: "mistralai/mistral-small-2603", name: "Mistral: Mistral Small 4" },
    { id: "z-ai/glm-5-turbo", name: "Z.ai: GLM 5 Turbo" },
    { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "NVIDIA: Nemotron 3 Super (free)" },
    { id: "nvidia/nemotron-3-super-120b-a12b", name: "NVIDIA: Nemotron 3 Super" },
    { id: "bytedance-seed/seed-2.0-lite", name: "ByteDance Seed: Seed-2.0-Lite" },
    { id: "qwen/qwen3.5-9b", name: "Qwen: Qwen3.5-9B" },
    { id: "openai/gpt-5.4-pro", name: "OpenAI: GPT-5.4 Pro" },
    { id: "openai/gpt-5.4", name: "OpenAI: GPT-5.4" },
    { id: "inception/mercury-2", name: "Inception: Mercury 2" },
    { id: "openai/gpt-5.3-chat", name: "OpenAI: GPT-5.3 Chat" },
    { id: "google/gemini-3.1-flash-lite-preview", name: "Google: Gemini 3.1 Flash Lite Preview" },
    { id: "bytedance-seed/seed-2.0-mini", name: "ByteDance Seed: Seed-2.0-Mini" },
    { id: "google/gemini-3.1-flash-image-preview", name: "Google: Nano Banana 2 (Gemini 3.1 Flash Image Preview)" },
    { id: "qwen/qwen3.5-35b-a3b", name: "Qwen: Qwen3.5-35B-A3B" },
    { id: "qwen/qwen3.5-27b", name: "Qwen: Qwen3.5-27B" },
    { id: "qwen/qwen3.5-122b-a10b", name: "Qwen: Qwen3.5-122B-A10B" },
    { id: "qwen/qwen3.5-flash-02-23", name: "Qwen: Qwen3.5-Flash" },
    { id: "liquid/lfm-2-24b-a2b", name: "LiquidAI: LFM2-24B-A2B" },
    { id: "google/gemini-3.1-pro-preview-customtools", name: "Google: Gemini 3.1 Pro Preview Custom Tools" },
    { id: "openai/gpt-5.3-codex", name: "OpenAI: GPT-5.3-Codex" },
    { id: "aion-labs/aion-2.0", name: "AionLabs: Aion-2.0" },
    { id: "google/gemini-3.1-pro-preview", name: "Google: Gemini 3.1 Pro Preview" },
    { id: "anthropic/claude-sonnet-4.6", name: "Anthropic: Claude Sonnet 4.6" },
    { id: "qwen/qwen3.5-plus-02-15", name: "Qwen: Qwen3.5 Plus 2026-02-15" },
    { id: "qwen/qwen3.5-397b-a17b", name: "Qwen: Qwen3.5 397B A17B" },
    { id: "minimax/minimax-m2.5", name: "MiniMax: MiniMax M2.5" },
    { id: "z-ai/glm-5", name: "Z.ai: GLM 5" },
    { id: "qwen/qwen3-max-thinking", name: "Qwen: Qwen3 Max Thinking" },
    { id: "anthropic/claude-opus-4.6", name: "Anthropic: Claude Opus 4.6" },
    { id: "qwen/qwen3-coder-next", name: "Qwen: Qwen3 Coder Next" },
    { id: "openrouter/free", name: "Free Models Router" },
    { id: "stepfun/step-3.5-flash", name: "StepFun: Step 3.5 Flash" },
    { id: "moonshotai/kimi-k2.5", name: "MoonshotAI: Kimi K2.5" },
    { id: "upstage/solar-pro-3", name: "Upstage: Solar Pro 3" },
    { id: "minimax/minimax-m2-her", name: "MiniMax: MiniMax M2-her" },
    { id: "writer/palmyra-x5", name: "Writer: Palmyra X5" },
    { id: "liquid/lfm-2.5-1.2b-thinking:free", name: "LiquidAI: LFM2.5-1.2B-Thinking (free)" },
    { id: "liquid/lfm-2.5-1.2b-instruct:free", name: "LiquidAI: LFM2.5-1.2B-Instruct (free)" },
    { id: "openai/gpt-audio", name: "OpenAI: GPT Audio" },
    { id: "openai/gpt-audio-mini", name: "OpenAI: GPT Audio Mini" },
    { id: "z-ai/glm-4.7-flash", name: "Z.ai: GLM 4.7 Flash" },
    { id: "openai/gpt-5.2-codex", name: "OpenAI: GPT-5.2-Codex" },
    { id: "bytedance-seed/seed-1.6-flash", name: "ByteDance Seed: Seed 1.6 Flash" },
    { id: "bytedance-seed/seed-1.6", name: "ByteDance Seed: Seed 1.6" },
    { id: "minimax/minimax-m2.1", name: "MiniMax: MiniMax M2.1" },
    { id: "z-ai/glm-4.7", name: "Z.ai: GLM 4.7" },
    { id: "google/gemini-3-flash-preview", name: "Google: Gemini 3 Flash Preview" },
    { id: "xiaomi/mimo-v2-flash", name: "Xiaomi: MiMo-V2-Flash" },
    { id: "nvidia/nemotron-3-nano-30b-a3b:free", name: "NVIDIA: Nemotron 3 Nano 30B A3B (free)" },
    { id: "nvidia/nemotron-3-nano-30b-a3b", name: "NVIDIA: Nemotron 3 Nano 30B A3B" },
    { id: "openai/gpt-5.2-chat", name: "OpenAI: GPT-5.2 Chat" },
    { id: "openai/gpt-5.2-pro", name: "OpenAI: GPT-5.2 Pro" },
    { id: "openai/gpt-5.2", name: "OpenAI: GPT-5.2" },
    { id: "mistralai/devstral-2512", name: "Mistral: Devstral 2 2512" },
    { id: "relace/relace-search", name: "Relace: Relace Search" },
    { id: "z-ai/glm-4.6v", name: "Z.ai: GLM 4.6V" },
    { id: "nex-agi/deepseek-v3.1-nex-n1", name: "Nex AGI: DeepSeek V3.1 Nex N1" },
    { id: "essentialai/rnj-1-instruct", name: "EssentialAI: Rnj 1 Instruct" },
    { id: "openrouter/bodybuilder", name: "Body Builder (beta)" },
    { id: "openai/gpt-5.1-codex-max", name: "OpenAI: GPT-5.1-Codex-Max" },
    { id: "amazon/nova-2-lite-v1", name: "Amazon: Nova 2 Lite" },
    { id: "mistralai/ministral-14b-2512", name: "Mistral: Ministral 3 14B 2512" },
    { id: "mistralai/ministral-8b-2512", name: "Mistral: Ministral 3 8B 2512" },
    { id: "mistralai/ministral-3b-2512", name: "Mistral: Ministral 3 3B 2512" },
    { id: "mistralai/mistral-large-2512", name: "Mistral: Mistral Large 3 2512" },
    { id: "arcee-ai/trinity-mini", name: "Arcee AI: Trinity Mini" },
    { id: "deepseek/deepseek-v3.2", name: "DeepSeek: DeepSeek V3.2" },
    { id: "prime-intellect/intellect-3", name: "Prime Intellect: INTELLECT-3" },
    { id: "anthropic/claude-opus-4.5", name: "Anthropic: Claude Opus 4.5" },
    { id: "allenai/olmo-3-32b-think", name: "AllenAI: Olmo 3 32B Think" },
    { id: "google/gemini-3-pro-image-preview", name: "Google: Nano Banana Pro (Gemini 3 Pro Image Preview)" },
    { id: "deepcogito/cogito-v2.1-671b", name: "Deep Cogito: Cogito v2.1 671B" },
    { id: "openai/gpt-5.1", name: "OpenAI: GPT-5.1" },
    { id: "openai/gpt-5.1-chat", name: "OpenAI: GPT-5.1 Chat" },
    { id: "openai/gpt-5.1-codex", name: "OpenAI: GPT-5.1-Codex" },
    { id: "openai/gpt-5.1-codex-mini", name: "OpenAI: GPT-5.1-Codex-Mini" },
    { id: "moonshotai/kimi-k2-thinking", name: "MoonshotAI: Kimi K2 Thinking" },
    { id: "amazon/nova-premier-v1", name: "Amazon: Nova Premier 1.0" },
    { id: "perplexity/sonar-pro-search", name: "Perplexity: Sonar Pro Search" },
    { id: "mistralai/voxtral-small-24b-2507", name: "Mistral: Voxtral Small 24B 2507" },
    { id: "openai/gpt-oss-safeguard-20b", name: "OpenAI: gpt-oss-safeguard-20b" },
    { id: "nvidia/nemotron-nano-12b-v2-vl:free", name: "NVIDIA: Nemotron Nano 12B 2 VL (free)" },
    { id: "minimax/minimax-m2", name: "MiniMax: MiniMax M2" },
    { id: "qwen/qwen3-vl-32b-instruct", name: "Qwen: Qwen3 VL 32B Instruct" },
    { id: "ibm-granite/granite-4.0-h-micro", name: "IBM: Granite 4.0 Micro" },
    { id: "microsoft/phi-4-mini-instruct", name: "Microsoft: Phi 4 Mini Instruct" },
    { id: "openai/gpt-5-image-mini", name: "OpenAI: GPT-5 Image Mini" },
    { id: "anthropic/claude-haiku-4.5", name: "Anthropic: Claude Haiku 4.5" },
    { id: "qwen/qwen3-vl-8b-thinking", name: "Qwen: Qwen3 VL 8B Thinking" },
    { id: "qwen/qwen3-vl-8b-instruct", name: "Qwen: Qwen3 VL 8B Instruct" },
    { id: "openai/gpt-5-image", name: "OpenAI: GPT-5 Image" },
    { id: "openai/o3-deep-research", name: "OpenAI: o3 Deep Research" },
    { id: "openai/o4-mini-deep-research", name: "OpenAI: o4 Mini Deep Research" },
    { id: "nvidia/llama-3.3-nemotron-super-49b-v1.5", name: "NVIDIA: Llama 3.3 Nemotron Super 49B V1.5" },
    { id: "google/gemini-2.5-flash-image", name: "Google: Nano Banana (Gemini 2.5 Flash Image)" },
    { id: "qwen/qwen3-vl-30b-a3b-thinking", name: "Qwen: Qwen3 VL 30B A3B Thinking" },
    { id: "qwen/qwen3-vl-30b-a3b-instruct", name: "Qwen: Qwen3 VL 30B A3B Instruct" },
    { id: "openai/gpt-5-pro", name: "OpenAI: GPT-5 Pro" },
    { id: "z-ai/glm-4.6", name: "Z.ai: GLM 4.6" },
    { id: "anthropic/claude-sonnet-4.5", name: "Anthropic: Claude Sonnet 4.5" },
    { id: "deepseek/deepseek-v3.2-exp", name: "DeepSeek: DeepSeek V3.2 Exp" },
    { id: "thedrummer/cydonia-24b-v4.1", name: "TheDrummer: Cydonia 24B V4.1" },
    { id: "relace/relace-apply-3", name: "Relace: Relace Apply 3" },
    { id: "google/gemini-2.5-flash-lite-preview-09-2025", name: "Google: Gemini 2.5 Flash Lite Preview 09-2025" },
    { id: "qwen/qwen3-vl-235b-a22b-thinking", name: "Qwen: Qwen3 VL 235B A22B Thinking" },
    { id: "qwen/qwen3-vl-235b-a22b-instruct", name: "Qwen: Qwen3 VL 235B A22B Instruct" },
    { id: "qwen/qwen3-max", name: "Qwen: Qwen3 Max" },
    { id: "qwen/qwen3-coder-plus", name: "Qwen: Qwen3 Coder Plus" },
    { id: "openai/gpt-5-codex", name: "OpenAI: GPT-5 Codex" },
    { id: "deepseek/deepseek-v3.1-terminus", name: "DeepSeek: DeepSeek V3.1 Terminus" },
    { id: "qwen/qwen3-coder-flash", name: "Qwen: Qwen3 Coder Flash" },
    { id: "qwen/qwen3-next-80b-a3b-thinking", name: "Qwen: Qwen3 Next 80B A3B Thinking" },
    { id: "qwen/qwen3-next-80b-a3b-instruct:free", name: "Qwen: Qwen3 Next 80B A3B Instruct (free)" },
    { id: "qwen/qwen3-next-80b-a3b-instruct", name: "Qwen: Qwen3 Next 80B A3B Instruct" },
    { id: "qwen/qwen-plus-2025-07-28:thinking", name: "Qwen: Qwen Plus 0728 (thinking)" },
    { id: "qwen/qwen-plus-2025-07-28", name: "Qwen: Qwen Plus 0728" },
    { id: "nvidia/nemotron-nano-9b-v2:free", name: "NVIDIA: Nemotron Nano 9B V2 (free)" },
    { id: "nvidia/nemotron-nano-9b-v2", name: "NVIDIA: Nemotron Nano 9B V2" },
    { id: "moonshotai/kimi-k2-0905", name: "MoonshotAI: Kimi K2 0905" },
    { id: "qwen/qwen3-30b-a3b-thinking-2507", name: "Qwen: Qwen3 30B A3B Thinking 2507" },
    { id: "nousresearch/hermes-4-70b", name: "Nous: Hermes 4 70B" },
    { id: "nousresearch/hermes-4-405b", name: "Nous: Hermes 4 405B" },
    { id: "deepseek/deepseek-chat-v3.1", name: "DeepSeek: DeepSeek V3.1" },
    { id: "mistralai/mistral-medium-3.1", name: "Mistral: Mistral Medium 3.1" },
    { id: "baidu/ernie-4.5-vl-28b-a3b", name: "Baidu: ERNIE 4.5 VL 28B A3B" },
    { id: "z-ai/glm-4.5v", name: "Z.ai: GLM 4.5V" },
    { id: "ai21/jamba-large-1.7", name: "AI21: Jamba Large 1.7" },
    { id: "openai/gpt-5-chat", name: "OpenAI: GPT-5 Chat" },
    { id: "openai/gpt-5", name: "OpenAI: GPT-5" },
    { id: "openai/gpt-5-mini", name: "OpenAI: GPT-5 Mini" },
    { id: "openai/gpt-5-nano", name: "OpenAI: GPT-5 Nano" },
    { id: "openai/gpt-oss-120b:free", name: "OpenAI: gpt-oss-120b (free)" },
    { id: "openai/gpt-oss-120b", name: "OpenAI: gpt-oss-120b" },
    { id: "openai/gpt-oss-20b:free", name: "OpenAI: gpt-oss-20b (free)" },
    { id: "openai/gpt-oss-20b", name: "OpenAI: gpt-oss-20b" },
    { id: "anthropic/claude-opus-4.1", name: "Anthropic: Claude Opus 4.1" },
    { id: "mistralai/codestral-2508", name: "Mistral: Codestral 2508" },
    { id: "qwen/qwen3-coder-30b-a3b-instruct", name: "Qwen: Qwen3 Coder 30B A3B Instruct" },
    { id: "qwen/qwen3-30b-a3b-instruct-2507", name: "Qwen: Qwen3 30B A3B Instruct 2507" },
    { id: "z-ai/glm-4.5", name: "Z.ai: GLM 4.5" },
    { id: "z-ai/glm-4.5-air:free", name: "Z.ai: GLM 4.5 Air (free)" },
    { id: "z-ai/glm-4.5-air", name: "Z.ai: GLM 4.5 Air" },
    { id: "qwen/qwen3-235b-a22b-thinking-2507", name: "Qwen: Qwen3 235B A22B Thinking 2507" },
    { id: "z-ai/glm-4-32b", name: "Z.ai: GLM 4 32B " },
    { id: "qwen/qwen3-coder:free", name: "Qwen: Qwen3 Coder 480B A35B (free)" },
    { id: "qwen/qwen3-coder", name: "Qwen: Qwen3 Coder 480B A35B" },
    { id: "bytedance/ui-tars-1.5-7b", name: "ByteDance: UI-TARS 7B " },
    { id: "google/gemini-2.5-flash-lite", name: "Google: Gemini 2.5 Flash Lite" },
    { id: "qwen/qwen3-235b-a22b-2507", name: "Qwen: Qwen3 235B A22B Instruct 2507" },
    { id: "switchpoint/router", name: "Switchpoint Router" },
    { id: "moonshotai/kimi-k2", name: "MoonshotAI: Kimi K2 0711" },
    { id: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free", name: "Venice: Uncensored (free)" },
    { id: "tencent/hunyuan-a13b-instruct", name: "Tencent: Hunyuan A13B Instruct" },
    { id: "morph/morph-v3-large", name: "Morph: Morph V3 Large" },
    { id: "morph/morph-v3-fast", name: "Morph: Morph V3 Fast" },
    { id: "baidu/ernie-4.5-vl-424b-a47b", name: "Baidu: ERNIE 4.5 VL 424B A47B " },
    { id: "baidu/ernie-4.5-300b-a47b", name: "Baidu: ERNIE 4.5 300B A47B " },
    { id: "mistralai/mistral-small-3.2-24b-instruct", name: "Mistral: Mistral Small 3.2 24B" },
    { id: "minimax/minimax-m1", name: "MiniMax: MiniMax M1" },
    { id: "google/gemini-2.5-flash", name: "Google: Gemini 2.5 Flash" },
    { id: "google/gemini-2.5-pro", name: "Google: Gemini 2.5 Pro" },
    { id: "openai/o3-pro", name: "OpenAI: o3 Pro" },
    { id: "google/gemini-2.5-pro-preview", name: "Google: Gemini 2.5 Pro Preview 06-05" },
    { id: "deepseek/deepseek-r1-0528", name: "DeepSeek: R1 0528" },
    { id: "anthropic/claude-opus-4", name: "Anthropic: Claude Opus 4" },
    { id: "anthropic/claude-sonnet-4", name: "Anthropic: Claude Sonnet 4" },
    { id: "google/gemma-3n-e4b-it", name: "Google: Gemma 3n 4B" },
    { id: "mistralai/mistral-medium-3", name: "Mistral: Mistral Medium 3" },
    { id: "google/gemini-2.5-pro-preview-05-06", name: "Google: Gemini 2.5 Pro Preview 05-06" },
    { id: "arcee-ai/spotlight", name: "Arcee AI: Spotlight" },
    { id: "arcee-ai/maestro-reasoning", name: "Arcee AI: Maestro Reasoning" },
    { id: "arcee-ai/virtuoso-large", name: "Arcee AI: Virtuoso Large" },
    { id: "arcee-ai/coder-large", name: "Arcee AI: Coder Large" },
    { id: "meta-llama/llama-guard-4-12b", name: "Meta: Llama Guard 4 12B" },
    { id: "qwen/qwen3-30b-a3b", name: "Qwen: Qwen3 30B A3B" },
    { id: "qwen/qwen3-8b", name: "Qwen: Qwen3 8B" },
    { id: "qwen/qwen3-14b", name: "Qwen: Qwen3 14B" },
    { id: "qwen/qwen3-32b", name: "Qwen: Qwen3 32B" },
    { id: "qwen/qwen3-235b-a22b", name: "Qwen: Qwen3 235B A22B" },
    { id: "openai/o4-mini-high", name: "OpenAI: o4 Mini High" },
    { id: "openai/o3", name: "OpenAI: o3" },
    { id: "openai/o4-mini", name: "OpenAI: o4 Mini" },
    { id: "openai/gpt-4.1", name: "OpenAI: GPT-4.1" },
    { id: "openai/gpt-4.1-mini", name: "OpenAI: GPT-4.1 Mini" },
    { id: "openai/gpt-4.1-nano", name: "OpenAI: GPT-4.1 Nano" },
    { id: "meta-llama/llama-4-maverick", name: "Meta: Llama 4 Maverick" },
    { id: "meta-llama/llama-4-scout", name: "Meta: Llama 4 Scout" },
    { id: "deepseek/deepseek-chat-v3-0324", name: "DeepSeek: DeepSeek V3 0324" },
    { id: "openai/o1-pro", name: "OpenAI: o1-pro" },
    { id: "mistralai/mistral-small-3.1-24b-instruct", name: "Mistral: Mistral Small 3.1 24B" },
    { id: "google/gemma-3-4b-it", name: "Google: Gemma 3 4B" },
    { id: "google/gemma-3-12b-it", name: "Google: Gemma 3 12B" },
    { id: "cohere/command-a", name: "Cohere: Command A" },
    { id: "openai/gpt-4o-mini-search-preview", name: "OpenAI: GPT-4o-mini Search Preview" },
    { id: "openai/gpt-4o-search-preview", name: "OpenAI: GPT-4o Search Preview" },
    { id: "rekaai/reka-flash-3", name: "Reka Flash 3" },
    { id: "google/gemma-3-27b-it", name: "Google: Gemma 3 27B" },
    { id: "thedrummer/skyfall-36b-v2", name: "TheDrummer: Skyfall 36B V2" },
    { id: "perplexity/sonar-reasoning-pro", name: "Perplexity: Sonar Reasoning Pro" },
    { id: "perplexity/sonar-pro", name: "Perplexity: Sonar Pro" },
    { id: "perplexity/sonar-deep-research", name: "Perplexity: Sonar Deep Research" },
    { id: "mistralai/mistral-saba", name: "Mistral: Saba" },
    { id: "meta-llama/llama-guard-3-8b", name: "Llama Guard 3 8B" },
    { id: "openai/o3-mini-high", name: "OpenAI: o3 Mini High" },
    { id: "aion-labs/aion-1.0", name: "AionLabs: Aion-1.0" },
    { id: "aion-labs/aion-1.0-mini", name: "AionLabs: Aion-1.0-Mini" },
    { id: "aion-labs/aion-rp-llama-3.1-8b", name: "AionLabs: Aion-RP 1.0 (8B)" },
    { id: "qwen/qwen2.5-vl-72b-instruct", name: "Qwen: Qwen2.5 VL 72B Instruct" },
    { id: "qwen/qwen-plus", name: "Qwen: Qwen-Plus" },
    { id: "openai/o3-mini", name: "OpenAI: o3 Mini" },
    { id: "mistralai/mistral-small-24b-instruct-2501", name: "Mistral: Mistral Small 3" },
    { id: "deepseek/deepseek-r1-distill-qwen-32b", name: "DeepSeek: R1 Distill Qwen 32B" },
    { id: "perplexity/sonar", name: "Perplexity: Sonar" },
    { id: "deepseek/deepseek-r1-distill-llama-70b", name: "DeepSeek: R1 Distill Llama 70B" },
    { id: "deepseek/deepseek-r1", name: "DeepSeek: R1" },
    { id: "minimax/minimax-01", name: "MiniMax: MiniMax-01" },
    { id: "microsoft/phi-4", name: "Microsoft: Phi 4" },
    { id: "sao10k/l3.1-70b-hanami-x1", name: "Sao10K: Llama 3.1 70B Hanami x1" },
    { id: "deepseek/deepseek-chat", name: "DeepSeek: DeepSeek V3" },
    { id: "sao10k/l3.3-euryale-70b", name: "Sao10K: Llama 3.3 Euryale 70B" },
    { id: "openai/o1", name: "OpenAI: o1" },
    { id: "cohere/command-r7b-12-2024", name: "Cohere: Command R7B (12-2024)" },
    { id: "meta-llama/llama-3.3-70b-instruct:free", name: "Meta: Llama 3.3 70B Instruct (free)" },
    { id: "meta-llama/llama-3.3-70b-instruct", name: "Meta: Llama 3.3 70B Instruct" },
    { id: "amazon/nova-lite-v1", name: "Amazon: Nova Lite 1.0" },
    { id: "amazon/nova-micro-v1", name: "Amazon: Nova Micro 1.0" },
    { id: "amazon/nova-pro-v1", name: "Amazon: Nova Pro 1.0" },
    { id: "openai/gpt-4o-2024-11-20", name: "OpenAI: GPT-4o (2024-11-20)" },
    { id: "mistralai/mistral-large-2407", name: "Mistral Large 2407" },
    { id: "qwen/qwen-2.5-coder-32b-instruct", name: "Qwen2.5 Coder 32B Instruct" },
    { id: "thedrummer/unslopnemo-12b", name: "TheDrummer: UnslopNemo 12B" },
    { id: "anthropic/claude-3.5-haiku", name: "Anthropic: Claude 3.5 Haiku" },
    { id: "anthracite-org/magnum-v4-72b", name: "Magnum v4 72B" },
    { id: "qwen/qwen-2.5-7b-instruct", name: "Qwen: Qwen2.5 7B Instruct" },
    { id: "inflection/inflection-3-pi", name: "Inflection: Inflection 3 Pi" },
    { id: "inflection/inflection-3-productivity", name: "Inflection: Inflection 3 Productivity" },
    { id: "thedrummer/rocinante-12b", name: "TheDrummer: Rocinante 12B" },
    { id: "meta-llama/llama-3.2-1b-instruct", name: "Meta: Llama 3.2 1B Instruct" },
    { id: "meta-llama/llama-3.2-11b-vision-instruct", name: "Meta: Llama 3.2 11B Vision Instruct" },
    { id: "meta-llama/llama-3.2-3b-instruct:free", name: "Meta: Llama 3.2 3B Instruct (free)" },
    { id: "meta-llama/llama-3.2-3b-instruct", name: "Meta: Llama 3.2 3B Instruct" },
    { id: "qwen/qwen-2.5-72b-instruct", name: "Qwen2.5 72B Instruct" },
    { id: "cohere/command-r-08-2024", name: "Cohere: Command R (08-2024)" },
    { id: "cohere/command-r-plus-08-2024", name: "Cohere: Command R+ (08-2024)" },
    { id: "sao10k/l3.1-euryale-70b", name: "Sao10K: Llama 3.1 Euryale 70B v2.2" },
    { id: "nousresearch/hermes-3-llama-3.1-70b", name: "Nous: Hermes 3 70B Instruct" },
    { id: "nousresearch/hermes-3-llama-3.1-405b:free", name: "Nous: Hermes 3 405B Instruct (free)" },
    { id: "nousresearch/hermes-3-llama-3.1-405b", name: "Nous: Hermes 3 405B Instruct" },
    { id: "sao10k/l3-lunaris-8b", name: "Sao10K: Llama 3 8B Lunaris" },
    { id: "openai/gpt-4o-2024-08-06", name: "OpenAI: GPT-4o (2024-08-06)" },
    { id: "meta-llama/llama-3.1-8b-instruct", name: "Meta: Llama 3.1 8B Instruct" },
    { id: "meta-llama/llama-3.1-70b-instruct", name: "Meta: Llama 3.1 70B Instruct" },
    { id: "mistralai/mistral-nemo", name: "Mistral: Mistral Nemo" },
    { id: "openai/gpt-4o-mini", name: "OpenAI: GPT-4o-mini" },
    { id: "openai/gpt-4o-mini-2024-07-18", name: "OpenAI: GPT-4o-mini (2024-07-18)" },
    { id: "google/gemma-2-27b-it", name: "Google: Gemma 2 27B" },
    { id: "sao10k/l3-euryale-70b", name: "Sao10k: Llama 3 Euryale 70B v2.1" },
    { id: "nousresearch/hermes-2-pro-llama-3-8b", name: "NousResearch: Hermes 2 Pro - Llama-3 8B" },
    { id: "openai/gpt-4o", name: "OpenAI: GPT-4o" },
    { id: "openai/gpt-4o-2024-05-13", name: "OpenAI: GPT-4o (2024-05-13)" },
    { id: "meta-llama/llama-3-8b-instruct", name: "Meta: Llama 3 8B Instruct" },
    { id: "meta-llama/llama-3-70b-instruct", name: "Meta: Llama 3 70B Instruct" },
    { id: "mistralai/mixtral-8x22b-instruct", name: "Mistral: Mixtral 8x22B Instruct" },
    { id: "microsoft/wizardlm-2-8x22b", name: "WizardLM-2 8x22B" },
    { id: "openai/gpt-4-turbo", name: "OpenAI: GPT-4 Turbo" },
    { id: "anthropic/claude-3-haiku", name: "Anthropic: Claude 3 Haiku" },
    { id: "mistralai/mistral-large", name: "Mistral Large" },
    { id: "openai/gpt-4-turbo-preview", name: "OpenAI: GPT-4 Turbo Preview" },
    { id: "openai/gpt-3.5-turbo-0613", name: "OpenAI: GPT-3.5 Turbo (older v0613)" },
    { id: "openrouter/auto", name: "Auto Router" },
    { id: "openai/gpt-4-1106-preview", name: "OpenAI: GPT-4 Turbo (older v1106)" },
    { id: "openai/gpt-3.5-turbo-instruct", name: "OpenAI: GPT-3.5 Turbo Instruct" },
    { id: "openai/gpt-3.5-turbo-16k", name: "OpenAI: GPT-3.5 Turbo 16k" },
    { id: "mancer/weaver", name: "Mancer: Weaver (alpha)" },
    { id: "undi95/remm-slerp-l2-13b", name: "ReMM SLERP 13B" },
    { id: "gryphe/mythomax-l2-13b", name: "MythoMax 13B" },
    { id: "openai/gpt-3.5-turbo", name: "OpenAI: GPT-3.5 Turbo" },
    { id: "openai/gpt-4", name: "OpenAI: GPT-4" },
    { id: "openai/gpt-4-0314", name: "OpenAI: GPT-4 (older v0314)" },
  ],
  fmd: [
    { id: "gpt-5.5", name: "GPT-5.5" },
  ],
  "freemodel-dev": [
    { id: "gpt-5.5", name: "GPT-5.5" },
  ],
  bai: [
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5", name: "GLM 5" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2" },
  ],
  qiniu: [
    { id: "deepseek-v3", name: "DeepSeek V3" },
  ],
  morph: [
    { id: "morph-v3-fast", name: "Morph V3 Fast" },
    { id: "morph-compactor", name: "Morph Compactor" },
    { id: "morph-minimax27-230b", name: "Morph MiniMax 27 230B" },
    { id: "morph-qwen36-27b", name: "Morph Qwen 3.6 27B" },
    { id: "morph-qwen35-397b", name: "Morph Qwen 3.5 397B" },
    { id: "morph-embedding-v4", name: "Morph Embedding V4", type: "embedding" },
  ],
  openai: [
    // Flagship models
    { id: "gpt-5.4", name: "GPT-5.4" },
    { id: "gpt-5.4-mini", name: "GPT-5.4 Mini" },
    { id: "gpt-5.4-nano", name: "GPT-5.4 Nano" },
    { id: "gpt-5.2", name: "GPT-5.2" },
    { id: "gpt-5.1", name: "GPT-5.1" },
    { id: "gpt-5", name: "GPT-5" },
    { id: "gpt-5-mini", name: "GPT-5 Mini" },
    { id: "gpt-5-nano", name: "GPT-5 Nano" },
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o Mini" },
    { id: "gpt-4-turbo", name: "GPT-4 Turbo" },
    { id: "gpt-4.1", name: "GPT-4.1" },
    { id: "gpt-4.1-mini", name: "GPT-4.1 Mini" },
    { id: "gpt-4.1-nano", name: "GPT-4.1 Nano" },
    // Reasoning models
    { id: "o3", name: "O3" },
    { id: "o3-mini", name: "O3 Mini" },
    { id: "o3-pro", name: "O3 Pro" },
    { id: "o4-mini", name: "O4 Mini" },
    { id: "o1", name: "O1" },
    { id: "o1-mini", name: "O1 Mini" },
    // Embedding models
    { id: "text-embedding-3-large", name: "Text Embedding 3 Large", type: "embedding" },
    { id: "text-embedding-3-small", name: "Text Embedding 3 Small", type: "embedding" },
    { id: "text-embedding-ada-002", name: "Text Embedding Ada 002", type: "embedding" },
    // TTS models
    { id: "tts-1", name: "TTS-1", type: "tts" },
    { id: "tts-1-hd", name: "TTS-1 HD", type: "tts" },
    { id: "gpt-4o-mini-tts", name: "GPT-4o Mini TTS", type: "tts" },
    // STT models
    { id: "whisper-1", name: "Whisper 1", type: "stt", params: ["language", "response_format", "temperature", "prompt"] },
    { id: "gpt-4o-transcribe", name: "GPT-4o Transcribe", type: "stt", params: ["language", "response_format", "temperature", "prompt"] },
    { id: "gpt-4o-mini-transcribe", name: "GPT-4o Mini Transcribe", type: "stt", params: ["language", "response_format", "temperature", "prompt"] },
    // Image models
    { id: "gpt-image-1", name: "GPT Image 1", type: "image", params: ["n", "size", "quality", "response_format"] },
    { id: "dall-e-3", name: "DALL-E 3", type: "image", params: ["size", "quality", "style", "response_format"] },
    { id: "dall-e-2", name: "DALL-E 2", type: "image", params: ["n", "size", "response_format"] },
  ],
  anthropic: [
    { id: "claude-sonnet-4-20250514", name: "Claude Sonnet 4" },
    { id: "claude-opus-4-20250514", name: "Claude Opus 4" },
    { id: "claude-3-5-sonnet-20241022", name: "Claude 3.5 Sonnet" },
  ],
  gmi: [
    { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview", upstreamModelId: "google/gemini-3.1-flash-lite-preview" },
  ],
  "gmi-cloud": [
    { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview", upstreamModelId: "google/gemini-3.1-flash-lite-preview" },
  ],
  gemini: [
    // Gemini 3.5 series
    { id: "gemini-3.5-flash", name: "Gemini 3.5 Flash" },
    // Gemini 3.1 series
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview", upstreamModelId: "google/gemini-3.1-flash-lite-preview" },
    // Gemini 3 series
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    // Gemini 2.5 series
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite" },
    // Gemini 2.0 series (retiring June 1, 2026)
    { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash" },
    { id: "gemini-2.0-flash-lite", name: "Gemini 2.0 Flash Lite" },
    // Gemma series
    { id: "gemma-4-31b-it", name: "Gemma 4 31B IT" },

    // Embedding models
    { id: "gemini-embedding-2-preview", name: "Gemini Embedding 2 Preview", type: "embedding" },
    { id: "gemini-embedding-001", name: "Gemini Embedding 001", type: "embedding" },
    { id: "text-embedding-005", name: "Text Embedding 005", type: "embedding" },
    { id: "text-embedding-004", name: "Text Embedding 004 (Legacy)", type: "embedding" },
    // Image models (Nano Banana)
    { id: "gemini-3.1-flash-image-preview", name: "Gemini 3.1 Flash Image (Nano Banana 2)", type: "image", params: [] },
    { id: "gemini-3-pro-image-preview", name: "Gemini 3 Pro Image (Nano Banana Pro)", type: "image", params: [] },
    { id: "gemini-2.5-flash-image", name: "Gemini 2.5 Flash Image (Nano Banana)", type: "image", params: [] },
    // STT models (multimodal generateContent)
    { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro (Best)", type: "stt", params: ["language", "prompt"] },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", type: "stt", params: ["language", "prompt"] },
    { id: "gemini-2.5-flash-lite", name: "Gemini 2.5 Flash Lite (Cheapest)", type: "stt", params: ["language", "prompt"] },
    { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", type: "stt", params: ["language", "prompt"] },
  ],
  openrouter: [
    // Free LLM models imported/cross-checked from FreeLLMAPI catalog
    { id: "minimax/minimax-m2.5:free", name: "MiniMax M2.5 (Free)" },
    { id: "qwen/qwen3-coder:free", name: "Qwen3 Coder (Free)" },
    { id: "qwen/qwen3-next-80b-a3b-instruct:free", name: "Qwen3 Next 80B A3B Instruct (Free)" },
    { id: "deepseek/deepseek-v3.1:free", name: "DeepSeek V3.1 (Free)" },
    { id: "moonshotai/kimi-k2:free", name: "Kimi K2 (Free)" },
    { id: "z-ai/glm-4.5-air:free", name: "GLM 4.5 Air (Free)" },
    { id: "inclusionai/ling-2.6-flash:free", name: "Ling 2.6 Flash (Free)" },
    { id: "arcee-ai/trinity-large-preview:free", name: "Trinity Large Preview (Free)" },
    { id: "nvidia/nemotron-3-nano-30b-a3b:free", name: "NVIDIA Nemotron Nano 30B (Free)" },
    { id: "openai/gpt-oss-20b:free", name: "GPT OSS 20B (Free)" },
    { id: "meta-llama/llama-3.3-70b-instruct:free", name: "Llama 3.3 70B (Free)" },
    { id: "google/gemma-4-31b-it:free", name: "Gemma 4 31B IT (Free)" },
    { id: "nousresearch/hermes-3-llama-3.1-405b:free", name: "Hermes 3 Llama 3.1 405B (Free)" },
    // Embedding models
    { id: "openai/text-embedding-3-large", name: "OpenAI Text Embedding 3 Large", type: "embedding" },
    { id: "openai/text-embedding-3-small", name: "OpenAI Text Embedding 3 Small", type: "embedding" },
    { id: "openai/text-embedding-ada-002", name: "OpenAI Text Embedding Ada 002", type: "embedding" },
    { id: "qwen/qwen3-embedding-8b", name: "Qwen3 Embedding 8B", type: "embedding" },
    { id: "perplexity/pplx-embed-v1-4b", name: "Perplexity Embed V1 4B", type: "embedding" },
    { id: "perplexity/pplx-embed-v1-0.6b", name: "Perplexity Embed V1 0.6B", type: "embedding" },
    { id: "nvidia/llama-nemotron-embed-vl-1b-v2:free", name: "NVIDIA Nemotron Embed VL 1B V2 (Free)", type: "embedding" },
    // TTS models
    { id: "openai/gpt-4o-mini-tts", name: "GPT-4o Mini TTS", type: "tts" },
    { id: "openai/tts-1-hd",        name: "TTS-1 HD",        type: "tts" },
    { id: "openai/tts-1",           name: "TTS-1",           type: "tts" },
    // Image models
    { id: "openai/dall-e-3", name: "DALL-E 3 (via OpenRouter)", type: "image", params: ["size", "quality", "style", "response_format"] },
    { id: "openai/gpt-image-1", name: "GPT Image 1 (via OpenRouter)", type: "image", params: ["n", "size", "quality", "response_format"] },
    { id: "google/imagen-3.0-generate-002", name: "Imagen 3 (via OpenRouter)", type: "image", params: ["n", "size"] },
    { id: "black-forest-labs/FLUX.1-schnell", name: "FLUX.1 Schnell (via OpenRouter)", type: "image", params: ["n", "size"] },
    // Free LLM models
    { id: "poolside/laguna-m.1:free", name: "Poolside Laguna M.1 (Free)" },
    { id: "openai/gpt-oss-120b:free", name: "GPT OSS 120B (Free)" },
    { id: "nvidia/nemotron-3-super-120b-a12b:free", name: "NVIDIA Nemotron Super 120B (Free)" },
  ],
  glm: [
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "glm-4.7", name: "GLM 4.7" },
    { id: "glm-4.6v", name: "GLM 4.6V (Vision)" },
  ],
  "glm-cn": [
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "glm-5", name: "GLM 5" },
    { id: "glm-4.7", name: "GLM-4.7" },
    { id: "glm-4.6", name: "GLM-4.6" },
    { id: "glm-4.5-air", name: "GLM-4.5-Air" },
  ],
  kimi: [
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "kimi-k2.5-thinking", name: "Kimi K2.5 Thinking" },
    { id: "kimi-latest", name: "Kimi Latest" },
  ],
  minimax: [
    { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "MiniMax-M2.1", name: "MiniMax M2.1" },
    // Image models
    { id: "minimax-image-01", name: "MiniMax Image 01", type: "image", params: ["n", "size", "response_format"] },
  ],
  blackbox: [
    { id: "gpt-4o", name: "GPT-4o" },
    { id: "gpt-4o-mini", name: "GPT-4o mini" },
    { id: "claude-sonnet-4.6", name: "Claude Sonnet 4.6" },
    { id: "claude-sonnet-4.5", name: "Claude Sonnet 4.5" },
    { id: "claude-opus-4.6", name: "Claude Opus 4.6" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4.6 (Legacy)" },
    { id: "claude-opus-4-6", name: "Claude Opus 4.6 (Legacy)" },
    { id: "deepseek-chat", name: "DeepSeek Chat" },
    { id: "deepseek-v3-671b", name: "DeepSeek V3 671B" },
    { id: "deepseek-r1", name: "DeepSeek R1" },
    { id: "o1", name: "OpenAI o1" },
    { id: "o3-mini", name: "OpenAI o3-mini" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "qwen3-max", name: "Qwen3 Max" },
    { id: "qwen3-vl-plus", name: "Qwen3 VL Plus" },
  ],
  "minimax-cn": [
    { id: "MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "MiniMax-M2.1", name: "MiniMax M2.1" },
  ],
  alicode: [
    { id: "qwen3.5-plus", name: "Qwen3.5 Plus" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5", name: "GLM 5" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "qwen3-max-2026-01-23", name: "Qwen3 Max" },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "glm-4.7", name: "GLM 4.7" },
  ],
  "alicode-intl": [
    { id: "qwen3.5-plus", name: "Qwen3.5 Plus" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5", name: "GLM 5" },
    { id: "MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "glm-4.7", name: "GLM 4.7" },
  ],
  "alibaba-studio": [
    { id: "qwen3.7-plus", name: "Qwen3.7 Plus" },
    { id: "qwen3.7-max", name: "Qwen3.7 Max" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "glm-5.1", name: "GLM 5.1" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v3.2", name: "DeepSeek V3.2" },
    { id: "qwen3.6-flash", name: "Qwen3.6 Flash" },
    { id: "qwen3.6-plus", name: "Qwen3.6 Plus" },
    { id: "qwen3.5-flash", name: "Qwen3.5 Flash" },
    { id: "qwen3-coder-next", name: "Qwen3 Coder Next" },
    { id: "qwen3-coder-plus", name: "Qwen3 Coder Plus" },
    { id: "qwen3-coder-480b-a35b-instruct", name: "Qwen3 Coder 480B A35B Instruct" },
    { id: "qwen3-235b-a22b", name: "Qwen3 235B A22B" },
    { id: "qwen-plus-latest", name: "Qwen Plus Latest" },
    { id: "qwen-flash", name: "Qwen Flash" },
    { id: "qwen-max-2026-01-23", name: "Qwen Max 2026-01-23" },
  ],
  "volcengine-ark": [
    { id: "Doubao-Seed-2.0-Code", name: "Doubao-Seed-2.0-Code" },
    { id: "Doubao-Seed-2.0-pro", name: "Doubao-Seed-2.0-pro" },
    { id: "Doubao-Seed-2.0-lite", name: "Doubao-Seed-2.0-lite" },
    { id: "Doubao-Seed-Code", name: "Doubao-Seed-Code" },
    { id: "GLM-5.1", name: "GLM-5.1" },
    { id: "MiniMax-M2.7", name: "MiniMax-M2.7" },
    { id: "Kimi-K2.6", name: "Kimi-K2.6" },
    { id: "MiniMax-M2.5", name: "MiniMax-M2.5" },
    { id: "Kimi-K2.5", name: "Kimi-K2.5" },
    { id: "GLM-4.7", name: "GLM-4.7" },
    { id: "DeepSeek-V3.2", name: "DeepSeek-V3.2" },
  ],
  "cloudflare-ai": [
    { id: "@cf/meta/llama-3.2-1b-instruct", name: "Llama 3.2 1B Instruct" },
    { id: "@cf/meta/llama-3.2-3b-instruct", name: "Llama 3.2 3B Instruct" },
    { id: "@cf/meta/llama-3.1-8b-instruct-fp8-fast", name: "Llama 3.1 8B Instruct FP8 Fast" },
    { id: "@cf/meta/llama-3.1-8b-instruct-awq", name: "Llama 3.1 8B Instruct AWQ" },
    { id: "@cf/mistralai/mistral-small-3.1-24b-instruct", name: "Mistral Small 3.1 24B Instruct" },
    { id: "@cf/meta/llama-3.1-70b-instruct-fp8-fast", name: "Llama 3.1 70B Instruct FP8 Fast" },
    { id: "@cf/meta/llama-3.3-70b-instruct-fp8-fast", name: "Llama 3.3 70B Instruct FP8 Fast" },
    { id: "@cf/deepseek-ai/deepseek-r1-distill-qwen-32b", name: "DeepSeek R1 Distill Qwen 32B" },
    { id: "@cf/moonshotai/kimi-k2.5", name: "Kimi K2.5" },
    { id: "@cf/moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "@cf/zai-org/glm-4.7-flash", name: "GLM 4.7 Flash" },
    { id: "@cf/qwen/qwq-32b", name: "QwQ 32B" },
    { id: "@cf/qwen/qwen2.5-coder-32b-instruct", name: "Qwen 2.5 Coder 32B Instruct" },
    { id: "@cf/black-forest-labs/flux-2-klein-9b", name: "FLUX.2 Klein 9B", type: "image", params: ["size"] },
    { id: "@cf/black-forest-labs/flux-2-klein-4b", name: "FLUX.2 Klein 4B", type: "image", params: ["size"] },
    { id: "@cf/black-forest-labs/flux-2-dev", name: "FLUX.2 Dev", type: "image", params: ["size"] },
    { id: "@cf/leonardo/lucid-origin", name: "Lucid Origin", type: "image", params: ["size"] },
    { id: "@cf/leonardo/phoenix-1.0", name: "Phoenix 1.0", type: "image", params: ["size"] },
    { id: "@cf/black-forest-labs/flux-1-schnell", name: "FLUX.1 Schnell", type: "image", params: ["size"] },
    { id: "@cf/bytedance/stable-diffusion-xl-lightning", name: "SDXL Lightning", type: "image", params: ["size"] },
    { id: "@cf/lykon/dreamshaper-8-lcm", name: "DreamShaper 8 LCM", type: "image", params: ["size"] },
    { id: "@cf/runwayml/stable-diffusion-v1-5-img2img", name: "Stable Diffusion v1.5 Img2Img", type: "image", params: ["size"], capabilities: ["edit"] },
    { id: "@cf/runwayml/stable-diffusion-v1-5-inpainting", name: "Stable Diffusion v1.5 Inpainting", type: "image", params: ["size"], capabilities: ["edit", "mask"] },
    { id: "@cf/stabilityai/stable-diffusion-xl-base-1.0", name: "SDXL Base 1.0", type: "image", params: ["size"] },
  ],
  byteplus: [
    { id: "seed-2-0-pro-260328", name: "Seed 2.0 Pro" },
    { id: "seed-2-0-code-preview-260328", name: "Seed 2.0 Code Preview" },
    { id: "seed-2-0-mini-260215", name: "Seed 2.0 Mini" },
    { id: "seed-2-0-lite-260228", name: "Seed 2.0 Lite" },
    { id: "kimi-k2-thinking-251104", name: "Kimi K2 Thinking" },
    { id: "glm-4-7-251222", name: "GLM 4.7" },
    { id: "gpt-oss-120b-250805", name: "GPT-OSS-120B" },
  ],
  deepseek: [
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-chat", name: "DeepSeek V3.2 Chat" },
    { id: "deepseek-reasoner", name: "DeepSeek V3.2 Reasoner" },
  ],
  commandcode: [
    { id: "deepseek/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "moonshotai/Kimi-K2.6", name: "Kimi K2.6" },
    { id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5" },
    { id: "zai-org/GLM-5.1", name: "GLM 5.1" },
    { id: "zai-org/GLM-5", name: "GLM 5" },
    { id: "MiniMaxAI/MiniMax-M2.7", name: "MiniMax M2.7" },
    { id: "MiniMaxAI/MiniMax-M2.5", name: "MiniMax M2.5" },
    { id: "Qwen/Qwen3.6-Max-Preview", name: "Qwen 3.6 Max Preview" },
    { id: "Qwen/Qwen3.6-Plus", name: "Qwen 3.6 Plus" },
    { id: "stepfun/Step-3.5-Flash", name: "Step 3.5 Flash" },
  ],
  groq: [
    { id: "groq/compound", name: "Compound" },
    { id: "groq/compound-mini", name: "Compound Mini" },
    { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B" },
    { id: "meta-llama/llama-4-maverick-17b-128e-instruct", name: "Llama 4 Maverick" },
    { id: "qwen/qwen3-32b", name: "Qwen3 32B" },
    { id: "openai/gpt-oss-120b", name: "GPT-OSS 120B" },
    { id: "openai/gpt-oss-20b", name: "GPT-OSS 20B" },
    { id: "llama-3.1-8b-instant", name: "Llama 3.1 8B Instant" },
    // STT models
    { id: "whisper-large-v3", name: "Whisper Large v3", type: "stt", params: ["language", "response_format", "temperature", "prompt"] },
    { id: "whisper-large-v3-turbo", name: "Whisper Large v3 Turbo", type: "stt", params: ["language", "response_format", "temperature", "prompt"] },
    { id: "distil-whisper-large-v3-en", name: "Distil Whisper Large v3 EN", type: "stt", params: ["language", "response_format", "temperature", "prompt"] },
  ],
  xai: [
    { id: "grok-4", name: "Grok 4" },
    { id: "grok-4-fast-reasoning", name: "Grok 4 Fast Reasoning" },
    { id: "grok-code-fast-1", name: "Grok Code Fast" },
    { id: "grok-3", name: "Grok 3" },
    { id: "grok-2-image-1212", name: "Grok 2 Image", type: "image", params: ["n", "response_format"] },
  ],
  "xai-apikey": [
    { id: "grok-4", name: "Grok 4" },
    { id: "grok-4-fast-reasoning", name: "Grok 4 Fast Reasoning" },
    { id: "grok-code-fast-1", name: "Grok Code Fast" },
    { id: "grok-3", name: "Grok 3" },
    { id: "grok-2-image-1212", name: "Grok 2 Image", type: "image", params: ["n", "response_format"] },
  ],
  mistral: [
    { id: "mistral-large-latest", name: "Mistral Large 3" },
    { id: "codestral-latest", name: "Codestral" },
    { id: "devstral-latest", name: "Devstral" },
    { id: "magistral-medium-latest", name: "Magistral Medium" },
    { id: "mistral-medium-latest", name: "Mistral Medium 3" },
    { id: "mistral-embed", name: "Mistral Embed", type: "embedding" },
  ],
  perplexity: [
    { id: "sonar-pro", name: "Sonar Pro" },
    { id: "sonar", name: "Sonar" },
  ],
  together: [
    { id: "meta-llama/Llama-3.3-70B-Instruct-Turbo", name: "Llama 3.3 70B Turbo" },
    { id: "deepseek-ai/DeepSeek-R1", name: "DeepSeek R1" },
    { id: "Qwen/Qwen3-235B-A22B", name: "Qwen3 235B" },
    { id: "meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8", name: "Llama 4 Maverick" },
    { id: "BAAI/bge-large-en-v1.5", name: "BGE Large EN v1.5", type: "embedding" },
    { id: "togethercomputer/m2-bert-80M-8k-retrieval", name: "M2 BERT 80M 8K", type: "embedding" },
  ],
  fireworks: [
    { id: "accounts/fireworks/models/deepseek-v3p1", name: "DeepSeek V3.1" },
    { id: "accounts/fireworks/models/llama-v3p3-70b-instruct", name: "Llama 3.3 70B" },
    { id: "accounts/fireworks/models/qwen3-235b-a22b", name: "Qwen3 235B" },
    { id: "nomic-ai/nomic-embed-text-v1.5", name: "Nomic Embed Text v1.5", type: "embedding" },
  ],
  cerebras: [
    { id: "qwen-3-coder-480b", name: "Qwen3 Coder 480B" },
    { id: "llama-4-maverick-17b-128e-instruct", name: "Llama 4 Maverick" },
    { id: "gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "zai-glm-4.7", name: "ZAI GLM 4.7" },
    { id: "llama-3.3-70b", name: "Llama 3.3 70B" },
    { id: "llama-4-scout-17b-16e-instruct", name: "Llama 4 Scout" },
    { id: "qwen-3-235b-a22b-instruct-2507", name: "Qwen3 235B A22B" },
    { id: "qwen-3-32b", name: "Qwen3 32B" },
    { id: "llama3.1-8b", name: "Llama 3.1 8B" },
  ],
  sambanova: [
    { id: "DeepSeek-V3.2", name: "DeepSeek V3.2" },
    { id: "DeepSeek-V3.1", name: "DeepSeek V3.1" },
    { id: "DeepSeek-V3.1-cb", name: "DeepSeek V3.1 (CB)" },
    { id: "gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "Llama-4-Maverick-17B-128E-Instruct", name: "Llama 4 Maverick" },
    { id: "Meta-Llama-3.3-70B-Instruct", name: "Llama 3.3 70B" },
    { id: "gemma-3-12b-it", name: "Gemma 3 12B IT" },
  ],
  cohere: [
    { id: "command-r-plus-08-2024", name: "Command R+ (Aug 2024)" },
    { id: "command-r-08-2024", name: "Command R (Aug 2024)" },
    { id: "command-a-03-2025", name: "Command A (Mar 2025)" },
  ],
  nvidia: [
    { id: "deepseek-ai/deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "mistralai/mistral-large-3-675b-instruct-2512", name: "Mistral Large 3 675B" },
    { id: "moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "google/gemma-4-31b-it", name: "Gemma 4 31B IT" },
    { id: "meta/llama-4-maverick-17b-128e-instruct", name: "Llama 4 Maverick" },
    { id: "meta/llama-3.3-70b-instruct", name: "Llama 3.3 70B" },
    { id: "meta/llama-3.1-70b-instruct", name: "Llama 3.1 70B" },
    { id: "nvidia/nemotron-3-super-120b-a12b", name: "Nemotron 3 Super 120B" },
    { id: "nvidia/nemotron-3-nano-30b-a3b", name: "Nemotron 3 Nano 30B" },
    { id: "minimaxai/minimax-m2.7", name: "Minimax M2.7" },
    { id: "z-ai/glm4.7", name: "GLM 4.7" },
    { id: "nvidia/nv-embedqa-e5-v5", name: "NV EmbedQA E5 v5", type: "embedding" },
    // STT models
    { id: "nvidia/parakeet-ctc-1.1b-asr", name: "Parakeet CTC 1.1B", type: "stt", params: ["language"] },
  ],
  nebius: [
    { id: "meta-llama/Llama-3.3-70B-Instruct", name: "Llama 3.3 70B Instruct" },
    { id: "Qwen/Qwen3-Embedding-8B", name: "Qwen3 Embedding 8B", type: "embedding" },
  ],
  "voyage-ai": [
    { id: "voyage-3-large", name: "Voyage 3 Large", type: "embedding" },
    { id: "voyage-3.5", name: "Voyage 3.5", type: "embedding" },
    { id: "voyage-3.5-lite", name: "Voyage 3.5 Lite", type: "embedding" },
    { id: "voyage-code-3", name: "Voyage Code 3", type: "embedding" },
    { id: "voyage-finance-2", name: "Voyage Finance 2", type: "embedding" },
    { id: "voyage-law-2", name: "Voyage Law 2", type: "embedding" },
    { id: "voyage-multilingual-2", name: "Voyage Multilingual 2", type: "embedding" },
  ],
  siliconflow: [
    { id: "deepseek-ai/DeepSeek-V3.2", name: "DeepSeek V3.2" },
    { id: "deepseek-ai/DeepSeek-V3.1", name: "DeepSeek V3.1" },
    { id: "deepseek-ai/DeepSeek-R1", name: "DeepSeek R1" },
    { id: "Qwen/Qwen3-235B-A22B-Instruct-2507", name: "Qwen3 235B" },
    { id: "Qwen/Qwen3-Coder-480B-A35B-Instruct", name: "Qwen3 Coder 480B" },
    { id: "Qwen/Qwen3-32B", name: "Qwen3 32B" },
    { id: "moonshotai/Kimi-K2.5", name: "Kimi K2.5" },
    { id: "zai-org/GLM-4.7", name: "GLM 4.7" },
    { id: "openai/gpt-oss-120b", name: "GPT OSS 120B" },
    { id: "baidu/ERNIE-4.5-300B-A47B", name: "ERNIE 4.5 300B" },
  ],
  cwv: [
    { id: "xiaomimimo/mimo-v2.5", name: "Xiaomi MiMo V2.5" },
    { id: "moonshotai/kimi-k2.6", name: "Kimi K2.6" },
    { id: "deepseek/deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "minimax/minimax-m2.5", name: "MiniMax M2.5" },
    { id: "zai/glm-5.1", name: "GLM 5.1" },
  ],
  am: [
    { id: "am/claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "am/claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "am/glm-5", name: "GLM 5" },
  ],
  aimux: [
    { id: "am/claude-opus-4.7", name: "Claude Opus 4.7" },
    { id: "am/claude-opus-4.8", name: "Claude Opus 4.8" },
    { id: "am/glm-5", name: "GLM 5" },
  ],
  husada: [
    { id: "ag/gemini-3.5-flash-extra-low", name: "Gemini 3.5 Flash Extra Low" },
    { id: "ag/gemini-3-flash-agent", name: "Gemini 3 Flash Agent" },
    { id: "ag/gemini-3.5-flash-low", name: "Gemini 3.5 Flash Low" },
    { id: "ag/gemini-pro-agent", name: "Gemini Pro Agent" },
    { id: "ag/gemini-3.1-pro-low", name: "Gemini 3.1 Pro Low" },
    { id: "ag/gemini-3-flash", name: "Gemini 3 Flash" },
  ],
  routeway: [
    { id: "ling-2.6-flash:free", name: "Ling 2.6 Flash Free" },
    { id: "gemma-4-31b-it:free", name: "Gemma 4 31B IT Free" },
    { id: "step-3.5-flash:free", name: "Step 3.5 Flash Free" },
    { id: "nemotron-3-nano-30b-a3b:free", name: "Nemotron 3 Nano 30B A3B Free" },
    { id: "minimax-m2:free", name: "MiniMax M2 Free" },
    { id: "laguna-xs.2:free", name: "Laguna XS.2 Free" },
    { id: "laguna-m.1:free", name: "Laguna M.1 Free" },
    { id: "nemotron-nano-9b-v2:free", name: "Nemotron Nano 9B V2 Free" },
    { id: "gpt-oss-120b:free", name: "GPT OSS 120B Free" },
    { id: "glm-4.5-air:free", name: "GLM 4.5 Air Free" },
    { id: "llama-3.2-3b-instruct:free", name: "Llama 3.2 3B Instruct Free" },
    { id: "llama-3.2-1b-instruct:free", name: "Llama 3.2 1B Instruct Free" },
    { id: "llama-3.1-8b-instruct:free", name: "Llama 3.1 8B Instruct Free" },
    { id: "llama-3.3-70b-instruct:free", name: "Llama 3.3 70B Instruct Free" },
    { id: "mistral-nemo-instruct:free", name: "Mistral Nemo Instruct Free" },
  ],
  sr: [
    { id: "gpt-5.5", name: "GPT 5.5" },
    { id: "gpt-5.4", name: "GPT 5.4" },
    { id: "gpt-5.4-mini", name: "GPT 5.4 Mini" },
    { id: "gpt-5.3-codex", name: "GPT 5.3 Codex" },
    { id: "gpt-5.2", name: "GPT 5.2" },
    { id: "claude-opus-4-7", name: "Claude Opus 4 7" },
    { id: "claude-opus-4-6", name: "Claude Opus 4 6" },
    { id: "claude-sonnet-4-6", name: "Claude Sonnet 4 6" },
    { id: "deepseek-v4-pro", name: "Deepseek V4 Pro" },
    { id: "deepseek-v4-flash", name: "Deepseek V4 Flash" },
    { id: "deepseek-v3.2", name: "Deepseek V3.2" },
    { id: "deepseek-v3.2-exp", name: "Deepseek V3.2 Exp" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "qwen3.6-plus", name: "Qwen3.6 Plus" },
    { id: "qwen3-coder", name: "Qwen3 Coder" },
  ],
  "xiaomi-mimo": [
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2-omni", name: "MiMo V2 Omni" },
    { id: "mimo-v2-flash", name: "MiMo V2 Flash" },
  ],
  "mimo-sgp": [
    { id: "mimo-v2.5-pro", name: "MiMo V2.5 Pro" },
    { id: "mimo-v2.5", name: "MiMo V2.5" },
    { id: "mimo-v2-pro", name: "MiMo V2 Pro" },
    { id: "mimo-v2-omni", name: "MiMo V2 Omni" },
    { id: "mimo-v2-flash", name: "MiMo V2 Flash" },
  ],
  hyperbolic: [
    { id: "Qwen/QwQ-32B", name: "QwQ 32B" },
    { id: "deepseek-ai/DeepSeek-R1", name: "DeepSeek R1" },
    { id: "deepseek-ai/DeepSeek-V3", name: "DeepSeek V3" },
    { id: "meta-llama/Llama-3.3-70B-Instruct", name: "Llama 3.3 70B" },
    { id: "meta-llama/Llama-3.2-3B-Instruct", name: "Llama 3.2 3B" },
    { id: "Qwen/Qwen2.5-72B-Instruct", name: "Qwen 2.5 72B" },
    { id: "Qwen/Qwen2.5-Coder-32B-Instruct", name: "Qwen 2.5 Coder 32B" },
    { id: "NousResearch/Hermes-3-Llama-3.1-70B", name: "Hermes 3 70B" },
  ],
  pollinations: [
    { id: "openai-fast", name: "GPT-OSS 20B (Pollinations)" },
  ],
  llm7: [
    { id: "gpt-oss-20b", name: "GPT-OSS 20B" },
    { id: "codestral-latest", name: "Codestral" },
    { id: "GLM-4.6V-Flash", name: "GLM 4.6V Flash" },
    { id: "meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo", name: "Llama 3.1 8B Turbo (Pro)" },
    { id: "ministral-8b-2512", name: "Ministral 8B (Pro)" },
    { id: "devstral-small-2:24b-cloud", name: "Devstral Small 2 24B Cloud (Pro)" },
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash (Pro)" },
    { id: "deepseek-v3.1:671b-terminus", name: "DeepSeek V3.1 Terminus (Pro)" },
  ],
  ollama: [
    { id: "gpt-oss:120b", name: "GPT OSS 120B" },
    { id: "kimi-k2.5", name: "Kimi K2.5" },
    { id: "glm-5", name: "GLM 5" },
    { id: "minimax-m2.5", name: "MiniMax M2.5" },
    { id: "glm-4.7-flash", name: "GLM 4.7 Flash" },
    { id: "qwen3.5", name: "Qwen3.5" },
  ],
  vertex: [
    { id: "gemini-3.1-pro-preview", name: "Gemini 3.1 Pro Preview" },
    { id: "gemini-3.1-flash-lite-preview", name: "Gemini 3.1 Flash Lite Preview", upstreamModelId: "google/gemini-3.1-flash-lite-preview" },
    { id: "gemini-3-flash-preview", name: "Gemini 3 Flash Preview" },
    { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash" },
  ],
  "vertex-partner": [
    { id: "deepseek-ai/deepseek-v3.2-maas", name: "DeepSeek V3.2 (Vertex)" },
    { id: "qwen/qwen3-next-80b-a3b-thinking-maas", name: "Qwen3 Next 80B Thinking (Vertex)" },
    { id: "qwen/qwen3-next-80b-a3b-instruct-maas", name: "Qwen3 Next 80B Instruct (Vertex)" },
    { id: "zai-org/glm-5-maas", name: "GLM-5 (Vertex)" },
  ],
  "grok-web": [
    { id: "grok-3", name: "Grok 3" },
    { id: "grok-3-mini", name: "Grok 3 Mini (Thinking)" },
    { id: "grok-3-thinking", name: "Grok 3 Thinking" },
    { id: "grok-4", name: "Grok 4" },
    { id: "grok-4-mini", name: "Grok 4 Mini (Thinking)" },
    { id: "grok-4-thinking", name: "Grok 4 Thinking" },
    { id: "grok-4-heavy", name: "Grok 4 Heavy (SuperGrok)" },
    { id: "grok-4.1-mini", name: "Grok 4.1 Mini (Thinking)" },
    { id: "grok-4.1-fast", name: "Grok 4.1 Fast" },
    { id: "grok-4.1-expert", name: "Grok 4.1 Expert" },
    { id: "grok-4.1-thinking", name: "Grok 4.1 Thinking" },
    { id: "grok-4.2", name: "Grok 4.2 (4.20 Beta)" },
  ],
  "perplexity-web": [
    { id: "pplx-auto", name: "Perplexity Auto (Free)" },
    { id: "pplx-sonar", name: "Perplexity Sonar" },
    { id: "pplx-gpt", name: "GPT-5.4 (via Perplexity)" },
    { id: "pplx-gemini", name: "Gemini 3.1 Pro (via Perplexity)" },
    { id: "pplx-sonnet", name: "Claude Sonnet 4.6 (via Perplexity)" },
    { id: "pplx-opus", name: "Claude Opus 4.6 (via Perplexity)" },
    { id: "pplx-nemotron", name: "Nemotron 3 Super (via Perplexity)" },
  ],

  // TTS entries are loaded from ttsModels.js via buildTtsProviderModels()
  ...buildTtsProviderModels(),

  // Image providers
  nanobanana: [
    { id: "nanobanana-flash", name: "NanoBanana Flash", type: "image", params: ["n", "size"] },
    { id: "nanobanana-pro", name: "NanoBanana Pro", type: "image", params: ["n", "size"] },
  ],
  sdwebui: [
    { id: "stable-diffusion-v1-5", name: "Stable Diffusion v1.5", type: "image", params: ["n", "size"] },
    { id: "sdxl-base-1.0", name: "SDXL Base 1.0", type: "image", params: ["n", "size"] },
  ],
  comfyui: [
    { id: "flux-dev", name: "FLUX Dev", type: "image", params: ["n", "size"] },
    { id: "sdxl", name: "SDXL", type: "image", params: ["n", "size"] },
  ],
  huggingface: [
    { id: "black-forest-labs/FLUX.1-schnell", name: "FLUX.1 Schnell", type: "image", params: [] },
    { id: "stabilityai/stable-diffusion-xl-base-1.0", name: "SDXL Base 1.0", type: "image", params: [] },
    // STT models
    { id: "openai/whisper-large-v3", name: "Whisper Large v3 (HF)", type: "stt", params: ["language"] },
    { id: "openai/whisper-small", name: "Whisper Small (HF)", type: "stt", params: ["language"] },
  ],
  deepgram: [
    { id: "nova-3", name: "Nova 3", type: "stt", params: ["language"] },
    { id: "nova-2", name: "Nova 2", type: "stt", params: ["language"] },
    { id: "whisper-large", name: "Whisper Large", type: "stt", params: ["language"] },
  ],
  assemblyai: [
    { id: "universal-3-pro", name: "Universal 3 Pro", type: "stt", params: ["language"] },
    { id: "universal-2", name: "Universal 2", type: "stt", params: ["language"] },
  ],
  "fal-ai": [
    { id: "fal-ai/flux/schnell", name: "FLUX Schnell", type: "image", params: ["n", "size"] },
    { id: "fal-ai/flux/dev", name: "FLUX Dev", type: "image", params: ["n", "size"] },
    { id: "fal-ai/flux-pro/v1.1", name: "FLUX Pro v1.1", type: "image", params: ["n", "size"] },
    { id: "fal-ai/flux-pro/v1.1-ultra", name: "FLUX Pro v1.1 Ultra", type: "image", params: ["n", "size"] },
    { id: "fal-ai/recraft-v3", name: "Recraft V3", type: "image", params: ["n", "size", "style"] },
    { id: "fal-ai/ideogram/v2", name: "Ideogram V2", type: "image", params: ["n", "size", "style"] },
    { id: "fal-ai/stable-diffusion-v35-large", name: "SD 3.5 Large", type: "image", params: ["n", "size"] },
  ],
  "stability-ai": [
    { id: "stable-image-ultra", name: "Stable Image Ultra", type: "image", params: ["size"] },
    { id: "stable-image-core", name: "Stable Image Core", type: "image", params: ["size", "style"] },
    { id: "sd3.5-large", name: "Stable Diffusion 3.5 Large", type: "image", params: ["size"] },
    { id: "sd3.5-large-turbo", name: "Stable Diffusion 3.5 Large Turbo", type: "image", params: ["size"] },
    { id: "sd3.5-medium", name: "Stable Diffusion 3.5 Medium", type: "image", params: ["size"] },
  ],
  "black-forest-labs": [
    { id: "flux-pro-1.1", name: "FLUX Pro 1.1", type: "image", params: ["n", "size"] },
    { id: "flux-pro-1.1-ultra", name: "FLUX Pro 1.1 Ultra", type: "image", params: ["size"] },
    { id: "flux-pro", name: "FLUX Pro", type: "image", params: ["n", "size"] },
    { id: "flux-dev", name: "FLUX Dev", type: "image", params: ["n", "size"] },
    { id: "flux-kontext-pro", name: "FLUX Kontext Pro (Edit)", type: "image", params: ["size"], capabilities: ["edit"] },
    { id: "flux-kontext-max", name: "FLUX Kontext Max (Edit)", type: "image", params: ["size"], capabilities: ["edit"] },
  ],
  recraft: [
    { id: "recraftv3", name: "Recraft V3", type: "image", params: ["n", "size", "style"] },
    { id: "recraftv2", name: "Recraft V2", type: "image", params: ["n", "size", "style"] },
  ],
  runwayml: [
    { id: "gen4_image", name: "Gen-4 Image", type: "image", params: ["size"] },
    { id: "gen4_image_turbo", name: "Gen-4 Image Turbo", type: "image", params: ["size"] },
    { id: "gen4_turbo", name: "Gen-4 Turbo", type: "video", params: [] },
    { id: "gen3a_turbo", name: "Gen-3 Alpha Turbo", type: "video", params: [] },
  ],
  fb: [
    { id: "deepseek-v4-flash", name: "DeepSeek V4 Flash" },
    { id: "deepseek-v4-pro", name: "DeepSeek V4 Pro" },
    { id: "kimi-k2.6", name: "Kimi K2.6" },
    { id: "minimax-m2.7", name: "MiniMax M2.7" },
  ],
};

// Helper functions
export function getProviderModels(aliasOrId) {
  return PROVIDER_MODELS[aliasOrId] || [];
}

export function getDefaultModel(aliasOrId) {
  const models = PROVIDER_MODELS[aliasOrId];
  return models?.[0]?.id || null;
}

export function isValidModel(aliasOrId, modelId, passthroughProviders = new Set()) {
  if (passthroughProviders.has(aliasOrId)) return true;
  const models = PROVIDER_MODELS[aliasOrId];
  if (!models) return false;
  return models.some(m => m.id === modelId);
}

export function findModelName(aliasOrId, modelId) {
  const models = PROVIDER_MODELS[aliasOrId];
  if (!models) return modelId;
  const found = models.find(m => m.id === modelId);
  return found?.name || modelId;
}

export function getModelTargetFormat(aliasOrId, modelId) {
  const models = PROVIDER_MODELS[aliasOrId];
  if (!models) return null;
  const found = models.find(m => m.id === modelId);
  return found?.targetFormat || null;
}

export function getModelUpstreamId(aliasOrId, modelId) {
  const models = PROVIDER_MODELS[aliasOrId];
  const found = models?.find(m => m.id === modelId);
  if (found?.upstreamModelId) return found.upstreamModelId;
  if (aliasOrId === "cx" && typeof modelId === "string" && modelId.endsWith(CODEX_REVIEW_SUFFIX)) {
    return modelId.slice(0, -CODEX_REVIEW_SUFFIX.length);
  }
  return modelId;
}

export function getModelQuotaFamily(aliasOrId, modelId) {
  const models = PROVIDER_MODELS[aliasOrId];
  const found = models?.find(m => m.id === modelId);
  return found?.quotaFamily || "normal";
}

// OAuth providers that use short aliases (everything else: alias = id)
const OAUTH_ALIASES = {
  claude: "cc",
  codex: "cx",
  "gemini-cli": "gc",
  qwen: "qw",
  "nous-portal": "nous",
  iflow: "if",
  antigravity: "ag",
  github: "gh",
  kiro: "kr",
  qoder: "qd",
  cursor: "cu",
  "kimi-coding": "kmc",
  codebuddy: "cb",
  kilocode: "kc",
  cline: "cl",
  opencode: "oc",
  gitlawb: "glb",
  "gitlawb-mimo": "glb-mimo",
  vertex: "vertex",
  "vertex-partner": "vertex-partner",
  canopywave: "cwv",
  "xiaomi-mimo-plan-sgp": "mimo-sgp",
  swiftrouter: "sr",
  freebuff: "fb",
};

// Derived from PROVIDERS — no need to maintain manually
export const PROVIDER_ID_TO_ALIAS = Object.fromEntries(
  Object.keys(PROVIDERS).map(id => [id, OAUTH_ALIASES[id] || id])
);

export function getModelsByProviderId(providerId) {
  const alias = PROVIDER_ID_TO_ALIAS[providerId] || providerId;
  return PROVIDER_MODELS[alias] || [];
}

// Get strip list for a model entry (explicit opt-in only)
// Returns array of content types to strip, e.g. ["image", "audio"]
export function getModelStrip(alias, modelId) {
  const entry = PROVIDER_MODELS[alias]?.find(m => m.id === modelId);
  return entry?.strip || [];
}
